# Generated by Django 5.2.8 on 2025-11-27 08:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationAgenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("heure_debut_journee", models.TimeField(default="08:00")),
                ("heure_fin_journee", models.TimeField(default="18:00")),
                ("heure_cloture_auto", models.TimeField(default="23:59")),
                (
                    "jours_travail",
                    models.JSONField(default=list, help_text="Jours de travail [0-6]"),
                ),
                (
                    "duree_rdv_defaut",
                    models.IntegerField(
                        default=60, help_text="Durée par défaut des RDV en minutes"
                    ),
                ),
                (
                    "rappel_rdv_defaut",
                    models.CharField(
                        choices=[
                            ("15min", "15 minutes avant"),
                            ("30min", "30 minutes avant"),
                            ("1h", "1 heure avant"),
                            ("1jour", "1 jour avant"),
                            ("personnalise", "Personnalisé"),
                        ],
                        default="1h",
                        max_length=20,
                    ),
                ),
                (
                    "rappel_tache_defaut",
                    models.CharField(
                        choices=[
                            ("jour_echeance", "Jour de l'échéance"),
                            ("veille", "La veille"),
                        ],
                        default="jour_echeance",
                        max_length=20,
                    ),
                ),
                ("envoyer_recapitulatif_quotidien", models.BooleanField(default=True)),
                ("heure_recapitulatif", models.TimeField(default="07:00")),
                ("activer_notifications_email", models.BooleanField(default=True)),
                ("activer_notifications_sms", models.BooleanField(default=False)),
                ("activer_cloture_auto", models.BooleanField(default=True)),
                ("reporter_auto_taches", models.BooleanField(default=True)),
                (
                    "delai_escalade_retard",
                    models.IntegerField(
                        default=2, help_text="Jours de retard avant escalade"
                    ),
                ),
                (
                    "couleurs_types_rdv",
                    models.JSONField(
                        default=dict, help_text="Couleurs par type de RDV"
                    ),
                ),
                (
                    "couleurs_types_tache",
                    models.JSONField(
                        default=dict, help_text="Couleurs par type de tâche"
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration de l'agenda",
                "verbose_name_plural": "Configuration de l'agenda",
            },
        ),
        migrations.CreateModel(
            name="DocumentTache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="agenda/tache_documents/"
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document de tâche",
                "verbose_name_plural": "Documents de tâche",
                "ordering": ["-date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="Etiquette",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                ("couleur", models.CharField(default="#3498db", max_length=7)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Étiquette",
                "verbose_name_plural": "Étiquettes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAgenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_objet",
                    models.CharField(
                        choices=[
                            ("rendez_vous", "Rendez-vous"),
                            ("tache", "Tâche"),
                            ("delegation", "Délégation"),
                            ("commentaire", "Commentaire"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.CharField(max_length=36)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("suppression", "Suppression"),
                            ("delegation", "Délégation"),
                            ("reassignation", "Réassignation"),
                            ("completion", "Complétion"),
                            ("report", "Report"),
                            ("annulation", "Annulation"),
                            ("commentaire", "Ajout commentaire"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("anciennes_valeurs", models.JSONField(blank=True, null=True)),
                ("nouvelles_valeurs", models.JSONField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historique agenda",
                "verbose_name_plural": "Historiques agenda",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="JourneeAgenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("nb_rdv_prevus", models.IntegerField(default=0)),
                ("nb_rdv_termines", models.IntegerField(default=0)),
                ("nb_rdv_annules", models.IntegerField(default=0)),
                ("nb_taches_prevues", models.IntegerField(default=0)),
                ("nb_taches_terminees", models.IntegerField(default=0)),
                ("nb_taches_reportees", models.IntegerField(default=0)),
                ("est_cloturee", models.BooleanField(default=False)),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                (
                    "type_cloture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automatique", "Automatique"),
                            ("manuelle", "Manuelle"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("commentaire_cloture", models.TextField(blank=True, null=True)),
                ("bilan_json", models.JSONField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journée agenda",
                "verbose_name_plural": "Journées agenda",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("nouveau_rdv", "Nouveau rendez-vous assigné"),
                            ("nouvelle_tache", "Nouvelle tâche déléguée"),
                            ("rappel_rdv", "Rappel de rendez-vous"),
                            ("rappel_tache", "Rappel de tâche"),
                            ("tache_retard", "Tâche en retard"),
                            ("tache_terminee", "Tâche terminée"),
                            ("demande_aide", "Demande d'aide"),
                            ("commentaire", "Nouveau commentaire"),
                            ("report", "Report automatique"),
                            ("bilan_journee", "Bilan de journée"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=36, null=True)),
                ("est_lu", models.BooleanField(default=False)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("application", "Notification dans l'application"),
                            ("tous", "Tous les canaux"),
                        ],
                        default="application",
                        max_length=20,
                    ),
                ),
                ("est_envoye_email", models.BooleanField(default=False)),
                ("est_envoye_sms", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantExterne",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "type_participant",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("debiteur", "Débiteur"),
                            ("avocat", "Avocat"),
                            ("notaire", "Notaire"),
                            ("expert", "Expert"),
                            ("temoin", "Témoin"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Participant externe",
                "verbose_name_plural": "Participants externes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="RappelRdv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_rappel",
                    models.CharField(
                        choices=[
                            ("15min", "15 minutes avant"),
                            ("30min", "30 minutes avant"),
                            ("1h", "1 heure avant"),
                            ("1jour", "1 jour avant"),
                            ("personnalise", "Personnalisé"),
                        ],
                        default="1h",
                        max_length=20,
                    ),
                ),
                (
                    "delai_personnalise",
                    models.IntegerField(
                        blank=True,
                        help_text="Délai en minutes si type personnalisé",
                        null=True,
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("application", "Notification dans l'application"),
                            ("tous", "Tous les canaux"),
                        ],
                        default="application",
                        max_length=20,
                    ),
                ),
                ("est_envoye", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rappel de rendez-vous",
                "verbose_name_plural": "Rappels de rendez-vous",
                "ordering": ["type_rappel"],
            },
        ),
        migrations.CreateModel(
            name="RappelTache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_rappel",
                    models.CharField(
                        choices=[
                            ("jour_echeance", "Jour de l'échéance"),
                            ("veille", "La veille"),
                            ("2jours", "2 jours avant"),
                            ("semaine", "Une semaine avant"),
                            ("personnalise", "Personnalisé"),
                        ],
                        default="jour_echeance",
                        max_length=20,
                    ),
                ),
                (
                    "delai_personnalise",
                    models.IntegerField(
                        blank=True,
                        help_text="Délai en jours si type personnalisé",
                        null=True,
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("application", "Notification dans l'application"),
                            ("tous", "Tous les canaux"),
                        ],
                        default="application",
                        max_length=20,
                    ),
                ),
                ("est_envoye", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rappel de tâche",
                "verbose_name_plural": "Rappels de tâche",
                "ordering": ["type_rappel"],
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "type_rdv",
                    models.CharField(
                        choices=[
                            ("rendez_vous_client", "Rendez-vous client"),
                            ("audience_tribunal", "Audience tribunal"),
                            ("signification", "Signification d'acte"),
                            ("constat", "Constat"),
                            ("saisie", "Saisie"),
                            ("expulsion", "Expulsion"),
                            ("reunion_interne", "Réunion interne"),
                            ("rdv_exterieur", "Rendez-vous extérieur"),
                            ("autre", "Autre"),
                        ],
                        default="rendez_vous_client",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("journee_entiere", models.BooleanField(default=False)),
                ("lieu", models.CharField(blank=True, max_length=255, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("confirme", "Confirmé"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("reporte", "Reporté"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                    ),
                ),
                ("couleur", models.CharField(default="#3498db", max_length=7)),
                (
                    "type_recurrence",
                    models.CharField(
                        choices=[
                            ("unique", "Unique"),
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("personnalise", "Personnalisé"),
                        ],
                        default="unique",
                        max_length=20,
                    ),
                ),
                (
                    "jours_semaine",
                    models.JSONField(
                        blank=True,
                        help_text="Jours de la semaine pour récurrence hebdomadaire [0-6]",
                        null=True,
                    ),
                ),
                (
                    "jour_mois",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("date_fin_recurrence", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="ReportTache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_origine", models.DateField()),
                ("nouvelle_date", models.DateField()),
                ("raison", models.TextField(blank=True, null=True)),
                (
                    "type_report",
                    models.CharField(
                        choices=[
                            ("automatique", "Automatique (clôture journée)"),
                            ("manuel", "Manuel"),
                        ],
                        default="manuel",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Report de tâche",
                "verbose_name_plural": "Reports de tâches",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="SousTacheChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("est_complete", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
                ("date_completion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Élément de checklist",
                "verbose_name_plural": "Éléments de checklist",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="StatistiquesAgenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_periode",
                    models.CharField(
                        choices=[
                            ("jour", "Jour"),
                            ("semaine", "Semaine"),
                            ("mois", "Mois"),
                            ("annee", "Année"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("nb_rdv_total", models.IntegerField(default=0)),
                ("nb_rdv_termines", models.IntegerField(default=0)),
                ("nb_rdv_annules", models.IntegerField(default=0)),
                ("nb_rdv_reportes", models.IntegerField(default=0)),
                ("repartition_types_rdv", models.JSONField(default=dict)),
                ("nb_taches_total", models.IntegerField(default=0)),
                ("nb_taches_terminees", models.IntegerField(default=0)),
                ("nb_taches_en_retard", models.IntegerField(default=0)),
                ("nb_taches_reportees", models.IntegerField(default=0)),
                ("repartition_types_tache", models.JSONField(default=dict)),
                (
                    "taux_realisation_rdv",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "taux_realisation_taches",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "temps_moyen_completion",
                    models.IntegerField(default=0, help_text="Temps moyen en minutes"),
                ),
                ("nb_taches_deleguees", models.IntegerField(default=0)),
                (
                    "taux_completion_delegations",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Statistiques agenda",
                "verbose_name_plural": "Statistiques agenda",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "type_tache",
                    models.CharField(
                        choices=[
                            ("redaction_acte", "Rédaction d'acte"),
                            ("signification", "Signification"),
                            ("appel_telephonique", "Appel téléphonique"),
                            ("envoi_courrier", "Envoi de courrier"),
                            ("relance", "Relance"),
                            ("recherche", "Recherche / Vérification"),
                            ("preparation_dossier", "Préparation de dossier"),
                            ("facturation", "Facturation"),
                            ("encaissement", "Encaissement"),
                            ("suivi_procedure", "Suivi procédure"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_echeance", models.DateField()),
                ("heure_echeance", models.TimeField(blank=True, null=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_delegation", models.DateTimeField(blank=True, null=True)),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                    ),
                ),
                ("couleur", models.CharField(default="#3498db", max_length=7)),
                (
                    "temps_estime",
                    models.IntegerField(
                        blank=True, help_text="Temps estimé en minutes", null=True
                    ),
                ),
                (
                    "temps_passe",
                    models.IntegerField(default=0, help_text="Temps passé en minutes"),
                ),
                (
                    "progression",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("en_attente", "En attente (bloquée)"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                            ("reportee", "Reportée"),
                        ],
                        default="a_faire",
                        max_length=20,
                    ),
                ),
                (
                    "statut_delegation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assignee", "Assignée"),
                            ("acceptee", "Acceptée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("refusee", "Refusée"),
                            ("validee", "Validée par l'huissier"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "type_recurrence",
                    models.CharField(
                        choices=[
                            ("unique", "Unique"),
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("personnalise", "Personnalisé"),
                        ],
                        default="unique",
                        max_length=20,
                    ),
                ),
                ("jours_semaine", models.JSONField(blank=True, null=True)),
                (
                    "jour_mois",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("date_fin_recurrence", models.DateField(blank=True, null=True)),
                ("ordre", models.IntegerField(default=0)),
                ("instructions_delegation", models.TextField(blank=True, null=True)),
                ("demande_compte_rendu", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_terminaison", models.DateTimeField(blank=True, null=True)),
                ("est_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ["date_echeance", "-priorite", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="CommentaireTache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "type_commentaire",
                    models.CharField(
                        choices=[
                            ("commentaire", "Commentaire"),
                            ("question", "Question"),
                            ("reponse", "Réponse"),
                            ("compte_rendu", "Compte-rendu"),
                            ("demande_aide", "Demande d'aide"),
                            ("validation", "Validation"),
                        ],
                        default="commentaire",
                        max_length=30,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("est_prive", models.BooleanField(default=False)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires_taches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire de tâche",
                "verbose_name_plural": "Commentaires de tâches",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRdv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="agenda/rdv_documents/"
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de rendez-vous",
                "verbose_name_plural": "Documents de rendez-vous",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
