# Generated by Django 5.2.8 on 2025-11-28 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_initial"),
        (
            "gestion",
            "0005_permission_role_adresseipautorisee_adresseipbloquee_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationRdv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut_presence",
                    models.CharField(
                        choices=[
                            ("invite", "Invité"),
                            ("confirme", "Confirmé"),
                            ("decline", "Décliné"),
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("excuse", "Excusé"),
                        ],
                        default="invite",
                        max_length=20,
                    ),
                ),
                ("date_reponse", models.DateTimeField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                ("notifie", models.BooleanField(default=False)),
                ("date_notification", models.DateTimeField(blank=True, null=True)),
                (
                    "collaborateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_rdv",
                        to="gestion.collaborateur",
                    ),
                ),
                (
                    "participant_externe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_rdv",
                        to="agenda.participantexterne",
                    ),
                ),
                (
                    "rdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="agenda.rendezvous",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation RDV",
                "verbose_name_plural": "Participations RDV",
                "indexes": [
                    models.Index(
                        fields=["rdv", "statut_presence"],
                        name="agenda_part_rdv_id_c11dd5_idx",
                    ),
                    models.Index(
                        fields=["collaborateur", "statut_presence"],
                        name="agenda_part_collabo_42ce9d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("collaborateur__isnull", False),
                                ("participant_externe__isnull", True),
                            ),
                            models.Q(
                                ("collaborateur__isnull", True),
                                ("participant_externe__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="participation_rdv_one_participant_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VueSauvegardee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "filtres",
                    models.JSONField(
                        default=dict,
                        help_text="Filtres: {type, statut, priorite, collaborateur, date_debut, date_fin, etc.}",
                    ),
                ),
                ("est_par_defaut", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vues_agenda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue sauvegardée",
                "verbose_name_plural": "Vues sauvegardées",
                "ordering": ["ordre", "nom"],
                "unique_together": {("utilisateur", "nom")},
            },
        ),
    ]
