# Generated by Django 5.2.8 on 2025-11-27 21:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BienImmobilier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=200, verbose_name="Désignation"),
                ),
                (
                    "type_bien",
                    models.CharField(
                        choices=[
                            ("appartement", "Appartement"),
                            ("maison", "Maison"),
                            ("villa", "Villa"),
                            ("studio", "Studio"),
                            ("bureau", "Bureau"),
                            ("commerce", "Local commercial"),
                            ("entrepot", "Entrepôt"),
                            ("terrain", "Terrain"),
                            ("immeuble", "Immeuble entier"),
                            ("autre", "Autre"),
                        ],
                        default="appartement",
                        max_length=20,
                    ),
                ),
                ("adresse", models.TextField(verbose_name="Adresse complète")),
                ("quartier", models.CharField(blank=True, max_length=100, null=True)),
                ("ville", models.CharField(max_length=100)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Surface (m²)",
                    ),
                ),
                (
                    "nombre_pieces",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de pièces"
                    ),
                ),
                ("etage", models.CharField(blank=True, max_length=20, null=True)),
                ("meuble", models.BooleanField(default=False, verbose_name="Meublé")),
                ("parking", models.BooleanField(default=False)),
                ("garage", models.BooleanField(default=False)),
                ("jardin", models.BooleanField(default=False)),
                ("piscine", models.BooleanField(default=False)),
                ("climatisation", models.BooleanField(default=False)),
                ("gardiennage", models.BooleanField(default=False)),
                (
                    "loyer_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Loyer mensuel (XOF)",
                    ),
                ),
                (
                    "charges_mensuelles",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Charges (XOF)",
                    ),
                ),
                (
                    "depot_garantie",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Dépôt de garantie (XOF)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("loue", "Loué"),
                            ("reserve", "Réservé"),
                            ("travaux", "En travaux"),
                            ("vente", "En vente"),
                        ],
                        default="libre",
                        max_length=20,
                    ),
                ),
                (
                    "date_acquisition",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date acquisition mandat"
                    ),
                ),
                (
                    "date_fin_mandat",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date fin mandat"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bien immobilier",
                "verbose_name_plural": "Biens immobiliers",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="Locataire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_locataire",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("societe", "Société"),
                        ],
                        default="particulier",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("civilite", models.CharField(blank=True, max_length=10, null=True)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "lieu_naissance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nationalite", models.CharField(default="Béninoise", max_length=50)),
                ("type_piece", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "numero_piece",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_expiration_piece", models.DateField(blank=True, null=True)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "telephone_secondaire",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                ("employeur", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "revenu_mensuel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contact_urgence_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_urgence_telephone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "contact_urgence_lien",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("garant_nom", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "garant_telephone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("garant_adresse", models.TextField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Locataire",
                "verbose_name_plural": "Locataires",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Proprietaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_proprietaire",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("societe", "Société"),
                            ("sci", "SCI"),
                            ("association", "Association"),
                        ],
                        default="particulier",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Prénom"
                    ),
                ),
                ("civilite", models.CharField(blank=True, max_length=10, null=True)),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ville", models.CharField(max_length=100)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("pays", models.CharField(default="Bénin", max_length=50)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "telephone_secondaire",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "numero_ifu",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° IFU"
                    ),
                ),
                (
                    "numero_rccm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° RCCM"
                    ),
                ),
                ("banque", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_compte",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("iban", models.CharField(blank=True, max_length=34, null=True)),
                (
                    "taux_honoraires",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Taux honoraires (%)",
                    ),
                ),
                (
                    "mode_reversement",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                        ],
                        default="mensuel",
                        max_length=20,
                    ),
                ),
                (
                    "jour_reversement",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Jour de reversement"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Propriétaire",
                "verbose_name_plural": "Propriétaires",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Bail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Bail"
                    ),
                ),
                (
                    "type_bail",
                    models.CharField(
                        choices=[
                            ("habitation", "Habitation"),
                            ("commercial", "Commercial"),
                            ("professionnel", "Professionnel"),
                            ("mixte", "Mixte"),
                        ],
                        default="habitation",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "duree_mois",
                    models.PositiveIntegerField(verbose_name="Durée (mois)"),
                ),
                (
                    "loyer_mensuel",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Loyer mensuel"
                    ),
                ),
                (
                    "charges_mensuelles",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "depot_garantie",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "depot_verse",
                    models.BooleanField(default=False, verbose_name="Dépôt versé"),
                ),
                (
                    "jour_paiement",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Jour de paiement"
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="especes",
                        max_length=20,
                    ),
                ),
                ("date_derniere_revision", models.DateField(blank=True, null=True)),
                (
                    "taux_revision",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux révision (%)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("termine", "Terminé"),
                            ("resilie", "Résilié"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "motif_fin",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motif fin de bail"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baux",
                        to="gerance.bienimmobilier",
                    ),
                ),
                (
                    "locataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baux",
                        to="gerance.locataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bail",
                "verbose_name_plural": "Baux",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="EtatDesLieux",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_etat",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                    ),
                ),
                ("date_etat", models.DateField(default=django.utils.timezone.now)),
                (
                    "compteur_eau",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "compteur_electricite",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "compteur_gaz",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("observations", models.JSONField(default=dict)),
                ("nombre_cles", models.PositiveIntegerField(default=0)),
                ("detail_cles", models.TextField(blank=True, null=True)),
                (
                    "etat_general",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("bon", "Bon"),
                            ("moyen", "Moyen"),
                            ("mauvais", "Mauvais"),
                        ],
                        default="bon",
                        max_length=20,
                    ),
                ),
                ("signe_bailleur", models.BooleanField(default=False)),
                ("signe_locataire", models.BooleanField(default=False)),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "bail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etats_lieux",
                        to="gerance.bail",
                    ),
                ),
            ],
            options={
                "verbose_name": "État des lieux",
                "verbose_name_plural": "États des lieux",
                "ordering": ["-date_etat"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_incident",
                    models.CharField(
                        choices=[
                            ("panne", "Panne"),
                            ("sinistre", "Sinistre"),
                            ("travaux", "Travaux"),
                            ("reclamation", "Réclamation"),
                            ("autre", "Autre"),
                        ],
                        default="panne",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "date_signalement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                (
                    "cout_estime",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cout_reel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "a_charge_de",
                    models.CharField(
                        choices=[
                            ("proprietaire", "Propriétaire"),
                            ("locataire", "Locataire"),
                            ("partage", "Partagé"),
                        ],
                        default="proprietaire",
                        max_length=20,
                    ),
                ),
                (
                    "intervenant",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "telephone_intervenant",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("signale", "Signalé"),
                            ("en_cours", "En cours"),
                            ("resolu", "Résolu"),
                            ("annule", "Annulé"),
                        ],
                        default="signale",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "bail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="gerance.bail",
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="gerance.bienimmobilier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-date_signalement"],
            },
        ),
        migrations.CreateModel(
            name="Loyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mois", models.PositiveIntegerField(verbose_name="Mois (1-12)")),
                ("annee", models.PositiveIntegerField(verbose_name="Année")),
                ("date_echeance", models.DateField(verbose_name="Date échéance")),
                ("montant_loyer", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "montant_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reste_a_payer", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "penalites",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_payer", "À payer"),
                            ("paye", "Payé"),
                            ("partiel", "Partiellement payé"),
                            ("retard", "En retard"),
                            ("impaye", "Impayé"),
                            ("annule", "Annulé"),
                        ],
                        default="a_payer",
                        max_length=20,
                    ),
                ),
                ("date_paiement", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "bail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyers",
                        to="gerance.bail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyer",
                "verbose_name_plural": "Loyers",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("bail", "mois", "annee")},
            },
        ),
        migrations.AddField(
            model_name="bienimmobilier",
            name="proprietaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="biens",
                to="gerance.proprietaire",
            ),
        ),
        migrations.CreateModel(
            name="Quittance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("date_emission", models.DateField(default=django.utils.timezone.now)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("periode_debut", models.DateField()),
                ("periode_fin", models.DateField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "loyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quittances",
                        to="gerance.loyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quittance",
                "verbose_name_plural": "Quittances",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="ReversementProprietaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mois", models.PositiveIntegerField()),
                ("annee", models.PositiveIntegerField()),
                (
                    "total_loyers",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total loyers encaissés",
                    ),
                ),
                (
                    "honoraires",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honoraires de gestion",
                    ),
                ),
                (
                    "autres_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_reverse",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant reversé"
                    ),
                ),
                ("date_reversement", models.DateField(blank=True, null=True)),
                (
                    "mode_reversement",
                    models.CharField(
                        choices=[
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("especes", "Espèces"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("effectue", "Effectué"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "proprietaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversements",
                        to="gerance.proprietaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversement propriétaire",
                "verbose_name_plural": "Reversements propriétaires",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("proprietaire", "mois", "annee")},
            },
        ),
    ]
