# Generated by Django 5.2.8 on 2025-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerance", "0001_initial"),
        ("gestion", "0011_reversement_compte_tresorerie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bail",
            name="dossiers_contentieux",
            field=models.ManyToManyField(
                blank=True,
                help_text="Dossiers contentieux liés à ce bail (impayés, procédures d'expulsion, etc.)",
                related_name="baux_gerance",
                to="gestion.dossier",
                verbose_name="Dossiers contentieux",
            ),
        ),
    ]
