# Generated by Django 5.2.8 on 2025-11-27 21:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteBancaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du compte")),
                (
                    "numero",
                    models.CharField(max_length=50, verbose_name="Numéro de compte"),
                ),
                ("banque", models.CharField(max_length=100, verbose_name="Banque")),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("courant", "Compte Courant"),
                            ("epargne", "Compte Épargne"),
                            ("sequestre", "Compte Séquestre"),
                            ("caisse", "Caisse"),
                        ],
                        default="courant",
                        max_length=20,
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "solde_actuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "seuil_alerte",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000,
                        max_digits=15,
                        verbose_name="Seuil alerte",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("cloture", "Clôturé"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=34, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="BIC"
                    ),
                ),
                (
                    "contact_banque",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Contact banque",
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date ouverture"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date clôture"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Compte bancaire",
                "verbose_name_plural": "Comptes bancaires",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="AlerteTresorerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("seuil_bas", "Seuil bas atteint"),
                            ("echeance", "Échéance proche"),
                            ("anomalie", "Anomalie détectée"),
                            ("rapprochement", "Rapprochement requis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("danger", "Critique"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("lue", models.BooleanField(default=False)),
                ("traitee", models.BooleanField(default=False)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="tresorerie.comptebancaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte trésorerie",
                "verbose_name_plural": "Alertes trésorerie",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="MouvementTresorerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("encaissement", "Encaissement client"),
                            ("reversement", "Reversement créancier"),
                            ("honoraires", "Honoraires"),
                            ("frais_acte", "Frais d'acte"),
                            ("salaire", "Salaire"),
                            ("loyer", "Loyer"),
                            ("charges", "Charges"),
                            ("impot", "Impôt et taxes"),
                            ("fournitures", "Fournitures"),
                            ("transport", "Transport"),
                            ("virement_interne", "Virement interne"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "date_mouvement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du mouvement",
                    ),
                ),
                (
                    "date_valeur",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de valeur"
                    ),
                ),
                ("libelle", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("carte", "Carte bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("prelevement", "Prélèvement"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                (
                    "dossier_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Dossier"
                    ),
                ),
                (
                    "facture_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Facture"
                    ),
                ),
                (
                    "tiers",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Tiers"
                    ),
                ),
                (
                    "numero_piece",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° pièce"
                    ),
                ),
                (
                    "numero_cheque",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° chèque"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("annule", "Annulé"),
                            ("rapproche", "Rapproché"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="tresorerie.comptebancaire",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de trésorerie",
                "verbose_name_plural": "Mouvements de trésorerie",
                "ordering": ["-date_mouvement", "-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PrevisionTresorerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_prevision",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée prévue"),
                            ("sortie", "Sortie prévue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date_prevue", models.DateField(verbose_name="Date prévue")),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("unique", "Unique"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="unique",
                        max_length=20,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("encaissement", "Encaissement client"),
                            ("reversement", "Reversement créancier"),
                            ("honoraires", "Honoraires"),
                            ("frais_acte", "Frais d'acte"),
                            ("salaire", "Salaire"),
                            ("loyer", "Loyer"),
                            ("charges", "Charges"),
                            ("impot", "Impôt et taxes"),
                            ("fournitures", "Fournitures"),
                            ("transport", "Transport"),
                            ("virement_interne", "Virement interne"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("prevue", "Prévue"),
                            ("realisee", "Réalisée"),
                            ("annulee", "Annulée"),
                        ],
                        default="prevue",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previsions",
                        to="tresorerie.comptebancaire",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mouvement_realise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prevision_source",
                        to="tresorerie.mouvementtresorerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prévision de trésorerie",
                "verbose_name_plural": "Prévisions de trésorerie",
                "ordering": ["date_prevue"],
            },
        ),
        migrations.CreateModel(
            name="RapprochementBancaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début période")),
                ("date_fin", models.DateField(verbose_name="Date fin période")),
                (
                    "solde_releve",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Solde relevé bancaire",
                    ),
                ),
                (
                    "solde_comptable",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Solde comptable"
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Écart"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("valide", "Validé"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapprochements",
                        to="tresorerie.comptebancaire",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mouvements_rapproches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rapprochements",
                        to="tresorerie.mouvementtresorerie",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapprochement bancaire",
                "verbose_name_plural": "Rapprochements bancaires",
                "ordering": ["-date_fin"],
            },
        ),
    ]
