# Generated by Django 5.2.8 on 2025-11-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0010_encaissement_compte_tresorerie_and_more"),
        ("tresorerie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mouvementtresorerie",
            name="dossier_id",
        ),
        migrations.RemoveField(
            model_name="mouvementtresorerie",
            name="facture_id",
        ),
        migrations.AddField(
            model_name="comptebancaire",
            name="operateur_mobile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn_momo", "MTN Mobile Money"),
                    ("moov_money", "Moov Money"),
                    ("celtiis_cash", "Celtiis Cash"),
                    ("orange_money", "Orange Money"),
                    ("free_money", "Free Money"),
                    ("autre", "Autre"),
                ],
                help_text="Requis si le type de compte est Mobile Money",
                max_length=20,
                null=True,
                verbose_name="Opérateur Mobile Money",
            ),
        ),
        migrations.AddField(
            model_name="mouvementtresorerie",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_tresorerie",
                to="gestion.dossier",
                verbose_name="Dossier lié",
            ),
        ),
        migrations.AddField(
            model_name="mouvementtresorerie",
            name="facture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_tresorerie",
                to="gestion.facture",
                verbose_name="Facture liée",
            ),
        ),
        migrations.AlterField(
            model_name="comptebancaire",
            name="type_compte",
            field=models.CharField(
                choices=[
                    ("courant", "Compte Courant"),
                    ("epargne", "Compte Épargne"),
                    ("sequestre", "Compte Séquestre"),
                    ("caisse", "Caisse"),
                    ("mobile_money", "Mobile Money"),
                ],
                default="courant",
                max_length=20,
            ),
        ),
    ]
