# Generated by Django 5.2.8 on 2025-11-26 22:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciceComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouvert", "Ouvert"), ("cloture", "Clôturé")],
                        default="ouvert",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "est_premier_exercice",
                    models.BooleanField(default=False, verbose_name="Premier exercice"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exercice comptable",
                "verbose_name_plural": "Exercices comptables",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="CompteComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° de compte"
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("1", "Classe 1 - Capitaux"),
                            ("2", "Classe 2 - Immobilisations"),
                            ("3", "Classe 3 - Stocks"),
                            ("4", "Classe 4 - Tiers"),
                            ("5", "Classe 5 - Trésorerie"),
                            ("6", "Classe 6 - Charges"),
                            ("7", "Classe 7 - Produits"),
                            ("8", "Classe 8 - Comptes spéciaux"),
                        ],
                        max_length=1,
                        verbose_name="Classe",
                    ),
                ),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("general", "Compte général"),
                            ("auxiliaire", "Compte auxiliaire"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "solde_normal",
                    models.CharField(
                        choices=[("debiteur", "Débiteur"), ("crediteur", "Créditeur")],
                        max_length=10,
                        verbose_name="Solde normal",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description/Aide"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "compte_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_comptes",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte comptable",
                "verbose_name_plural": "Comptes comptables",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "est_configure",
                    models.BooleanField(
                        default=False, verbose_name="Configuration terminée"
                    ),
                ),
                (
                    "date_configuration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de configuration"
                    ),
                ),
                (
                    "mode_saisie_defaut",
                    models.CharField(
                        choices=[
                            ("facile", "Facile"),
                            ("guide", "Guidé"),
                            ("expert", "Expert"),
                        ],
                        default="facile",
                        max_length=10,
                        verbose_name="Mode de saisie par défaut",
                    ),
                ),
                (
                    "compte_banque_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte banque principal",
                    ),
                ),
                (
                    "compte_caisse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte caisse",
                    ),
                ),
                (
                    "compte_clients",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte clients",
                    ),
                ),
                (
                    "compte_fournisseurs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte fournisseurs",
                    ),
                ),
                (
                    "compte_honoraires",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte honoraires",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration comptable",
                "verbose_name_plural": "Configuration comptable",
            },
        ),
        migrations.CreateModel(
            name="DeclarationTVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode_debut", models.DateField(verbose_name="Début de période")),
                ("periode_fin", models.DateField(verbose_name="Fin de période")),
                (
                    "tva_collectee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="TVA collectée",
                    ),
                ),
                (
                    "tva_deductible",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="TVA déductible",
                    ),
                ),
                (
                    "tva_a_payer",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="TVA à payer",
                    ),
                ),
                (
                    "credit_tva",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Crédit de TVA",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("validee", "Validée"),
                            ("declaree", "Déclarée"),
                            ("payee", "Payée"),
                        ],
                        default="brouillon",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_declaration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de déclaration"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comptabilite.exercicecomptable",
                        verbose_name="Exercice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration TVA",
                "verbose_name_plural": "Déclarations TVA",
                "ordering": ["-periode_debut"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=5, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "type_journal",
                    models.CharField(
                        choices=[
                            ("AC", "Achats"),
                            ("VE", "Ventes"),
                            ("BQ", "Banque"),
                            ("CA", "Caisse"),
                            ("OD", "Opérations diverses"),
                            ("AN", "À nouveau"),
                            ("CL", "Clôture"),
                        ],
                        max_length=2,
                        verbose_name="Type",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "compte_contrepartie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte de contrepartie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journaux",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° pièce"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence externe"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("manuelle", "Saisie manuelle"),
                            ("facture", "Facture"),
                            ("tresorerie", "Trésorerie"),
                            ("automatique", "Automatique"),
                            ("cloture", "Clôture"),
                        ],
                        default="manuelle",
                        max_length=15,
                        verbose_name="Origine",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_comptables",
                        to="gestion.dossier",
                        verbose_name="Dossier lié",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_comptables",
                        to="gestion.facture",
                        verbose_name="Facture liée",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comptabilite.exercicecomptable",
                        verbose_name="Exercice",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comptabilite.journal",
                        verbose_name="Journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "ordering": ["-date", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="LigneEcriture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Débit"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Crédit",
                    ),
                ),
                (
                    "tiers",
                    models.CharField(blank=True, max_length=200, verbose_name="Tiers"),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite.ecriturecomptable",
                        verbose_name="Écriture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ParametrageFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        max_digits=5,
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "periodicite_declaration_tva",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                        ],
                        default="mensuel",
                        max_length=20,
                        verbose_name="Périodicité déclaration TVA",
                    ),
                ),
                (
                    "seuil_paiement_especes",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("100000"),
                        max_digits=15,
                        verbose_name="Seuil paiement espèces (FCFA)",
                    ),
                ),
                (
                    "compte_tva_a_payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte TVA à payer",
                    ),
                ),
                (
                    "compte_tva_collectee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte TVA collectée",
                    ),
                ),
                (
                    "compte_tva_deductible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte TVA déductible",
                    ),
                ),
                (
                    "exercice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametres_fiscaux",
                        to="comptabilite.exercicecomptable",
                        verbose_name="Exercice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramétrage fiscal",
                "verbose_name_plural": "Paramétrages fiscaux",
            },
        ),
        migrations.CreateModel(
            name="RapportComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("bilan", "Bilan"),
                            ("resultat", "Compte de résultat"),
                            ("grand_livre", "Grand livre"),
                            ("balance", "Balance"),
                            ("journal", "Journal"),
                            ("flux_tresorerie", "Flux de trésorerie"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                ("periode_debut", models.DateField(verbose_name="Début de période")),
                ("periode_fin", models.DateField(verbose_name="Fin de période")),
                ("donnees", models.JSONField(verbose_name="Données du rapport")),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comptabilite.exercicecomptable",
                        verbose_name="Exercice",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Généré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport comptable",
                "verbose_name_plural": "Rapports comptables",
                "ordering": ["-date_generation"],
            },
        ),
        migrations.CreateModel(
            name="TypeOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(verbose_name="Description pour l'utilisateur"),
                ),
                (
                    "icone",
                    models.CharField(
                        default="file-text", max_length=50, verbose_name="Icône Lucide"
                    ),
                ),
                (
                    "ordre_affichage",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "compte_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_credit",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte à créditer",
                    ),
                ),
                (
                    "compte_debit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_debit",
                        to="comptabilite.comptecomptable",
                        verbose_name="Compte à débiter",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comptabilite.journal",
                        verbose_name="Journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type d'opération",
                "verbose_name_plural": "Types d'opérations",
                "ordering": ["ordre_affichage", "libelle"],
            },
        ),
    ]
