# Generated by Django 5.2.8 on 2025-11-29 06:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion", "0009_add_commercant_fields_personne_physique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierRecouvrement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_recouvrement",
                    models.CharField(
                        choices=[
                            ("amiable", "Recouvrement amiable"),
                            ("force", "Recouvrement forcé"),
                        ],
                        default="amiable",
                        max_length=20,
                        verbose_name="Type de recouvrement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("suspendu", "Suspendu"),
                            ("cloture", "Clôturé"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "motif_cloture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recouvre", "Créance recouvrée"),
                            ("irrecoverable", "Créance irrécouvrable"),
                            ("abandon", "Abandon par le créancier"),
                            ("prescription", "Prescription"),
                            ("transaction", "Transaction"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Motif de clôture",
                    ),
                ),
                (
                    "montant_principal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant principal",
                    ),
                ),
                (
                    "montant_interets",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Intérêts",
                    ),
                ),
                (
                    "frais_procedure",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Frais de procédure",
                    ),
                ),
                (
                    "emoluments",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Émoluments",
                    ),
                ),
                (
                    "honoraires_amiable",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Honoraires (phase amiable)",
                    ),
                ),
                (
                    "montant_encaisse",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant encaissé",
                    ),
                ),
                (
                    "montant_reverse",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant reversé",
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'ouverture",
                    ),
                ),
                (
                    "date_effet_interets",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date effet intérêts"
                    ),
                ),
                (
                    "date_decision_executoire",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date décision exécutoire"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                (
                    "derniere_action",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dernière action"
                    ),
                ),
                (
                    "prochaine_etape",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Prochaine étape"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "creancier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers_recouvrement",
                        to="gestion.creancier",
                        verbose_name="Créancier",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_recouvrement_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debiteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_debiteur",
                        to="gestion.partie",
                        verbose_name="Débiteur",
                    ),
                ),
                (
                    "dossier_principal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier principal de l'étude lié à ce recouvrement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_recouvrement",
                        to="gestion.dossier",
                        verbose_name="Dossier juridique principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de recouvrement",
                "verbose_name_plural": "Dossiers de recouvrement",
                "ordering": ["-date_ouverture", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="EnvoiAutomatiquePoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actif", models.BooleanField(default=False)),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("hebdomadaire", "Hebdomadaire"),
                            ("bimensuel", "Bimensuel"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                        ],
                        default="mensuel",
                        max_length=20,
                    ),
                ),
                (
                    "jour_envoi",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Jour du mois (1-28)"
                    ),
                ),
                (
                    "destinataires",
                    models.TextField(help_text="Emails séparés par des virgules"),
                ),
                ("dernier_envoi", models.DateTimeField(blank=True, null=True)),
                ("prochain_envoi", models.DateTimeField(blank=True, null=True)),
                ("inclure_en_cours", models.BooleanField(default=True)),
                ("inclure_clotures", models.BooleanField(default=False)),
                (
                    "creancier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_envoi_point",
                        to="gestion.creancier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration envoi automatique",
                "verbose_name_plural": "Configurations envois automatiques",
            },
        ),
        migrations.CreateModel(
            name="PointGlobalCreancier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                ("periode_debut", models.DateField(verbose_name="Début période")),
                ("periode_fin", models.DateField(verbose_name="Fin période")),
                ("inclure_tous_dossiers", models.BooleanField(default=True)),
                ("inclure_en_cours", models.BooleanField(default=True)),
                ("inclure_clotures", models.BooleanField(default=True)),
                ("inclure_amiable", models.BooleanField(default=True)),
                ("inclure_force", models.BooleanField(default=True)),
                ("nombre_dossiers", models.PositiveIntegerField(default=0)),
                ("nombre_en_cours", models.PositiveIntegerField(default=0)),
                ("nombre_clotures_succes", models.PositiveIntegerField(default=0)),
                ("nombre_clotures_echec", models.PositiveIntegerField(default=0)),
                ("nombre_amiable", models.PositiveIntegerField(default=0)),
                ("nombre_force", models.PositiveIntegerField(default=0)),
                (
                    "total_creances",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_encaisse",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_reverse",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_reste_du",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "taux_recouvrement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_frais_procedure",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_emoluments",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_honoraires_amiable",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "total_retenu",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "document_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="points_globaux/"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("genere", "Généré"),
                            ("envoye", "Envoyé au créancier"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "creancier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_globaux",
                        to="gestion.creancier",
                        verbose_name="Créancier",
                    ),
                ),
                (
                    "dossiers_selectionnes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="points_globaux_inclus",
                        to="recouvrement.dossierrecouvrement",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point global créancier",
                "verbose_name_plural": "Points globaux créanciers",
                "ordering": ["-date_generation"],
            },
        ),
    ]
