# Generated by Django 5.2.8 on 2025-11-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_reversement_compte_tresorerie_and_more"),
        ("recouvrement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointglobalcreancier",
            name="creancier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_globaux_recouvrement",
                to="gestion.creancier",
                verbose_name="Créancier",
            ),
        ),
    ]
