# Generated by Django 5.2.8 on 2025-11-29 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recouvrement", "0002_alter_pointglobalcreancier_creancier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="emoluments_calcules",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Émoluments calculés",
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="emoluments_imputes",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Émoluments déjà imputés",
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="frais_engages",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Frais engagés"
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="frais_imputes",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Frais déjà imputés",
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="interets_imputes",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Intérêts déjà imputés",
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="mode_facturation",
            field=models.CharField(
                choices=[
                    ("standard", "Standard - Imputation automatique"),
                    ("reserve", "Réservé - Imputation différée"),
                    ("banque", "Mode Banque - Reversement total + Facture"),
                ],
                default="standard",
                help_text="Standard=imputation auto, Réservé=différé, Banque=reversement total",
                max_length=20,
                verbose_name="Mode de facturation",
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="principal_impute",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Principal déjà imputé",
            ),
        ),
        migrations.AddField(
            model_name="dossierrecouvrement",
            name="total_reverse",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Total reversé au créancier",
            ),
        ),
        migrations.CreateModel(
            name="PaiementRecouvrement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_paiement", models.DateField(verbose_name="Date du paiement")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant reçu"
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile", "Mobile Money"),
                            ("autre", "Autre"),
                        ],
                        default="especes",
                        max_length=20,
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True,
                        help_text="N° chèque, référence virement, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "impute_frais",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Imputé sur frais",
                    ),
                ),
                (
                    "impute_emoluments",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Imputé sur émoluments",
                    ),
                ),
                (
                    "impute_interets",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Imputé sur intérêts",
                    ),
                ),
                (
                    "impute_principal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Imputé sur principal",
                    ),
                ),
                (
                    "montant_reserve",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant réservé (frais/émoluments différés)",
                    ),
                ),
                (
                    "montant_a_reverser",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant à reverser au créancier",
                    ),
                ),
                (
                    "est_reverse",
                    models.BooleanField(
                        default=False, verbose_name="Reversé au créancier"
                    ),
                ),
                ("date_reversement", models.DateField(blank=True, null=True)),
                ("reference_reversement", models.CharField(blank=True, max_length=100)),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_recouvrement_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="recouvrement.dossierrecouvrement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement recouvrement",
                "verbose_name_plural": "Paiements recouvrement",
                "ordering": ["-date_paiement", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImputationManuelle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_imputation", models.DateField(auto_now_add=True)),
                (
                    "type_imputation",
                    models.CharField(
                        choices=[
                            ("frais", "Frais"),
                            ("emoluments", "Émoluments"),
                            ("interets", "Intérêts"),
                            ("principal", "Principal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=0, max_digits=15)),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imputations_manuelles",
                        to="recouvrement.paiementrecouvrement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imputation manuelle",
                "verbose_name_plural": "Imputations manuelles",
                "ordering": ["-date_imputation"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueActionRecouvrement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("creation", "Création du dossier"),
                            ("mise_en_demeure", "Mise en demeure"),
                            ("relance", "Relance"),
                            ("appel", "Appel téléphonique"),
                            ("visite", "Visite sur place"),
                            ("sommation", "Sommation de payer"),
                            ("saisie", "Saisie"),
                            ("paiement", "Paiement reçu"),
                            ("reversement", "Reversement créancier"),
                            ("basculement", "Basculement amiable/forcé"),
                            ("cloture", "Clôture du dossier"),
                            ("autre", "Autre action"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_actions",
                        to="recouvrement.dossierrecouvrement",
                    ),
                ),
                (
                    "paiement_lie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recouvrement.paiementrecouvrement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique action",
                "verbose_name_plural": "Historique actions",
                "ordering": ["-date_action"],
            },
        ),
    ]
