# Generated by Django 5.2.8 on 2025-11-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion", "0010_encaissement_compte_tresorerie_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPortail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_client",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code client"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=50)),
                ("mot_de_passe", models.CharField(max_length=128)),
                (
                    "type_client",
                    models.CharField(
                        choices=[
                            ("creancier", "Créancier"),
                            ("debiteur", "Débiteur"),
                            ("autre", "Autre justiciable"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="Type de client",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(max_length=300, verbose_name="Nom complet"),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "email_verifie",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                ("token_verification", models.CharField(blank=True, max_length=100)),
                (
                    "date_derniere_connexion",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("tentatives_connexion", models.PositiveIntegerField(default=0)),
                (
                    "compte_bloque",
                    models.BooleanField(default=False, verbose_name="Compte bloqué"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compte_portail",
                        to="gestion.partie",
                        verbose_name="Partie liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client portail",
                "verbose_name_plural": "Clients portail",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccesDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("acte", "Acte formalisé"),
                            ("facture", "Facture"),
                            ("decompte", "Décompte"),
                            ("courrier", "Courrier"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                ("titre", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("fichier", models.FileField(upload_to="portail_documents/")),
                ("date_mise_disposition", models.DateTimeField(auto_now_add=True)),
                (
                    "date_premier_telechargement",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("nombre_telechargements", models.PositiveIntegerField(default=0)),
                (
                    "paiement_requis",
                    models.BooleanField(default=False, verbose_name="Paiement requis"),
                ),
                (
                    "montant_requis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant requis (FCFA)",
                    ),
                ),
                (
                    "est_paye",
                    models.BooleanField(default=False, verbose_name="Est payé"),
                ),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                ("reference_paiement", models.CharField(blank=True, max_length=100)),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.dossier",
                        verbose_name="Dossier lié",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_accessibles",
                        to="portail_client.clientportail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document accessible",
                "verbose_name_plural": "Documents accessibles",
                "ordering": ["-date_mise_disposition"],
            },
        ),
        migrations.CreateModel(
            name="DemandeContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom complet")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("en_cours", "En cours de traitement"),
                            ("traite", "Traité"),
                            ("archive", "Archivé"),
                        ],
                        default="nouveau",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes_internes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_contact_traitees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de contact",
                "verbose_name_plural": "Demandes de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessagePortail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=300, verbose_name="Sujet")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "est_de_client",
                    models.BooleanField(
                        default=True,
                        help_text="True = client vers étude, False = étude vers client",
                        verbose_name="Message du client",
                    ),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="portail_messages/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="portail_client.clientportail",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.dossier",
                        verbose_name="Dossier concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message portail",
                "verbose_name_plural": "Messages portail",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("nouveau_document", "Nouveau document disponible"),
                            ("mise_a_jour_dossier", "Mise à jour dossier"),
                            ("paiement_recu", "Paiement reçu"),
                            ("message", "Nouveau message"),
                            ("rappel", "Rappel"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "lien",
                    models.CharField(blank=True, max_length=500, verbose_name="Lien"),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="portail_client.clientportail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification client",
                "verbose_name_plural": "Notifications clients",
                "ordering": ["-created_at"],
            },
        ),
    ]
