# Generated by Django 5.2.8 on 2025-11-27 21:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueSauvegarde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "taille",
                    models.BigIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("reussi", "Réussi"),
                            ("echec", "Échec"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Emplacement"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
            ],
            options={
                "verbose_name": "Sauvegarde",
                "verbose_name_plural": "Historique des sauvegardes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="JourFerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du jour férié"),
                ),
                (
                    "date_fixe",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date (jours fixes)"
                    ),
                ),
                (
                    "jour_mois",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Jour du mois (récurrent)",
                    ),
                ),
                (
                    "mois",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mois (récurrent)",
                    ),
                ),
                (
                    "est_mobile",
                    models.BooleanField(
                        default=False, verbose_name="Date mobile (Pâques, etc.)"
                    ),
                ),
                (
                    "formule",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Formule de calcul (dates mobiles)",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
                "ordering": ["mois", "jour_mois", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Juridiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TPI", "Tribunal de Première Instance"),
                            ("CA", "Cour d'Appel"),
                            ("CC", "Cour de Cassation"),
                            ("TC", "Tribunal de Commerce"),
                            ("TT", "Tribunal du Travail"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Juridiction",
                "verbose_name_plural": "Juridictions",
                "ordering": ["type", "ville", "nom"],
            },
        ),
        migrations.CreateModel(
            name="SiteAgence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du site")),
                ("adresse", models.TextField(verbose_name="Adresse")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsable"
                    ),
                ),
                (
                    "est_principal",
                    models.BooleanField(default=False, verbose_name="Site principal"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Site/Agence",
                "verbose_name_plural": "Sites/Agences",
                "ordering": ["-est_principal", "nom"],
            },
        ),
        migrations.CreateModel(
            name="StatutDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "couleur",
                    models.CharField(
                        default="#1a365d", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "est_cloture",
                    models.BooleanField(
                        default=False, verbose_name="Est un statut de clôture"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statut de dossier",
                "verbose_name_plural": "Statuts de dossiers",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypeActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                (
                    "montant_defaut",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant par défaut",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Type d'acte",
                "verbose_name_plural": "Types d'actes",
                "ordering": ["categorie", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypeDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#1a365d", max_length=7, verbose_name="Couleur"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de dossier",
                "verbose_name_plural": "Types de dossiers",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_etude",
                    models.CharField(
                        default="Étude Me BIAOU",
                        max_length=200,
                        verbose_name="Nom de l'étude",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        default="Huissier de Justice",
                        max_length=100,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "juridiction",
                    models.CharField(
                        default="près le Tribunal de Première Instance de Parakou et la Cour d'Appel de Parakou",
                        max_length=300,
                        verbose_name="Juridiction",
                    ),
                ),
                (
                    "adresse_rue",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Adresse (rue)"
                    ),
                ),
                (
                    "adresse_quartier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Quartier"
                    ),
                ),
                (
                    "adresse_ville",
                    models.CharField(
                        default="Parakou", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "adresse_bp",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Boîte postale"
                    ),
                ),
                (
                    "telephone_fixe",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone fixe"
                    ),
                ),
                (
                    "telephone_mobile1",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mobile 1"
                    ),
                ),
                (
                    "telephone_mobile2",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mobile 2"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email professionnel"
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "numero_ifu",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Numéro IFU"
                    ),
                ),
                (
                    "numero_agrement",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Numéro d'agrément / Inscription au tableau",
                    ),
                ),
                (
                    "date_installation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'installation"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="etude/logos/",
                        verbose_name="Logo de l'étude",
                    ),
                ),
                (
                    "couleur_principale",
                    models.CharField(
                        default="#1a365d",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        default="#c6a962",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "banque_nom",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Banque principale"
                    ),
                ),
                (
                    "banque_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code banque"
                    ),
                ),
                (
                    "banque_guichet",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code guichet"
                    ),
                ),
                (
                    "banque_compte",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de compte"
                    ),
                ),
                (
                    "banque_cle",
                    models.CharField(blank=True, max_length=5, verbose_name="Clé RIB"),
                ),
                (
                    "banque_iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "banque_titulaire",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titulaire du compte"
                    ),
                ),
                (
                    "mobile_money_operateur",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Opérateur Mobile Money"
                    ),
                ),
                (
                    "mobile_money_numero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro Mobile Money"
                    ),
                ),
                (
                    "dossier_prefixe",
                    models.CharField(
                        default="DOS-",
                        max_length=10,
                        verbose_name="Préfixe numéros de dossier",
                    ),
                ),
                (
                    "dossier_numero_depart",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Numéro de départ nouvelle année"
                    ),
                ),
                (
                    "facture_prefixe",
                    models.CharField(
                        default="FAC-", max_length=10, verbose_name="Préfixe factures"
                    ),
                ),
                (
                    "tva_applicable",
                    models.BooleanField(default=True, verbose_name="TVA applicable"),
                ),
                (
                    "tva_taux",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "mecef_nim",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro NIM (MECeF)"
                    ),
                ),
                (
                    "mecef_token",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Token API MECeF"
                    ),
                ),
                (
                    "mecef_mode",
                    models.CharField(
                        choices=[("test", "Test"), ("production", "Production")],
                        default="test",
                        max_length=20,
                        verbose_name="Mode MECeF",
                    ),
                ),
                (
                    "facture_mentions_legales",
                    models.TextField(
                        blank=True, verbose_name="Mentions légales sur factures"
                    ),
                ),
                (
                    "facture_conditions_paiement",
                    models.CharField(
                        default="Payable à réception",
                        max_length=200,
                        verbose_name="Conditions de paiement",
                    ),
                ),
                (
                    "facture_delai_paiement",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Délai de paiement (jours)"
                    ),
                ),
                (
                    "facture_penalites_retard",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=5,
                        verbose_name="Pénalités de retard (% par mois)",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="FCFA", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "tresorerie_seuil_alerte",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000"),
                        max_digits=15,
                        verbose_name="Seuil alerte solde faible (F)",
                    ),
                ),
                (
                    "tresorerie_validation_seuil",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500000"),
                        max_digits=15,
                        verbose_name="Validation obligatoire décaissements > (F)",
                    ),
                ),
                (
                    "tresorerie_delai_reversement",
                    models.PositiveIntegerField(
                        default=30,
                        verbose_name="Délai max reversement consignations (jours)",
                    ),
                ),
                (
                    "tresorerie_compte_sequestre",
                    models.BooleanField(
                        default=True, verbose_name="Compte séquestre obligatoire"
                    ),
                ),
                (
                    "exercice_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début exercice comptable"
                    ),
                ),
                (
                    "exercice_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin exercice comptable"
                    ),
                ),
                (
                    "comptabilite_mode",
                    models.CharField(
                        choices=[
                            ("facile", "Facile"),
                            ("guide", "Guidé"),
                            ("expert", "Expert"),
                        ],
                        default="guide",
                        max_length=20,
                        verbose_name="Mode de saisie",
                    ),
                ),
                (
                    "regime_fiscal",
                    models.CharField(
                        choices=[
                            ("reel_normal", "Réel normal"),
                            ("reel_simplifie", "Réel simplifié"),
                            ("micro", "Micro"),
                        ],
                        default="reel_normal",
                        max_length=30,
                        verbose_name="Régime fiscal",
                    ),
                ),
                (
                    "tva_declaration",
                    models.CharField(
                        choices=[
                            ("mensuelle", "Mensuelle"),
                            ("trimestrielle", "Trimestrielle"),
                        ],
                        default="mensuelle",
                        max_length=20,
                        verbose_name="Déclarations TVA",
                    ),
                ),
                (
                    "echeances_rappel_jours",
                    models.PositiveIntegerField(
                        default=7,
                        verbose_name="Rappels échéances fiscales (jours avant)",
                    ),
                ),
                (
                    "recouvrement_majoration_50",
                    models.BooleanField(
                        default=True,
                        verbose_name="Application majoration 50% (Loi 2024)",
                    ),
                ),
                (
                    "recouvrement_delai_majoration",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Délai avant majoration (mois)"
                    ),
                ),
                (
                    "recouvrement_ordre_imputation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Ordre imputation paiements",
                    ),
                ),
                (
                    "gerance_taux_honoraires",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        verbose_name="Taux honoraires gestion (% loyer)",
                    ),
                ),
                (
                    "gerance_date_reversement",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                        verbose_name="Date reversement propriétaires",
                    ),
                ),
                (
                    "gerance_relance_niveau1",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Relance niveau 1 - Rappel (J+)"
                    ),
                ),
                (
                    "gerance_relance_niveau2",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Relance niveau 2 - Relance (J+)"
                    ),
                ),
                (
                    "gerance_relance_niveau3",
                    models.PositiveIntegerField(
                        default=30,
                        verbose_name="Relance niveau 3 - Mise en demeure (J+)",
                    ),
                ),
                (
                    "gerance_relance_niveau4",
                    models.PositiveIntegerField(
                        default=45, verbose_name="Relance niveau 4 - Commandement (J+)"
                    ),
                ),
                (
                    "rh_smig",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("52000"),
                        max_digits=15,
                        verbose_name="SMIG en vigueur (FCFA)",
                    ),
                ),
                (
                    "rh_cnss_salarial_vieillesse",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.6"),
                        max_digits=5,
                        verbose_name="CNSS Salarial Vieillesse (%)",
                    ),
                ),
                (
                    "rh_cnss_patronal_pf",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6.4"),
                        max_digits=5,
                        verbose_name="CNSS Patronal PF (%)",
                    ),
                ),
                (
                    "rh_cnss_patronal_vieillesse",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6.4"),
                        max_digits=5,
                        verbose_name="CNSS Patronal Vieillesse (%)",
                    ),
                ),
                (
                    "rh_cnss_patronal_at",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        max_digits=5,
                        verbose_name="CNSS Patronal AT (%)",
                    ),
                ),
                (
                    "rh_plafond_cnss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("600000"),
                        max_digits=15,
                        verbose_name="Plafond CNSS mensuel (FCFA)",
                    ),
                ),
                (
                    "rh_conges_annuels",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Congés annuels (jours/mois)"
                    ),
                ),
                (
                    "rh_heures_hebdo",
                    models.PositiveIntegerField(
                        default=40, verbose_name="Heures travail hebdomadaires"
                    ),
                ),
                (
                    "rh_jour_paie",
                    models.PositiveIntegerField(
                        default=28,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                        verbose_name="Jour de paie",
                    ),
                ),
                (
                    "cedules_residence",
                    models.CharField(
                        default="Parakou",
                        max_length=200,
                        verbose_name="Résidence de l'huissier",
                    ),
                ),
                (
                    "cedules_premier_original",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("980"),
                        max_digits=10,
                        verbose_name="Premier original (F)",
                    ),
                ),
                (
                    "cedules_deuxieme_original",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("980"),
                        max_digits=10,
                        verbose_name="Deuxième original (F)",
                    ),
                ),
                (
                    "cedules_copie",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("900"),
                        max_digits=10,
                        verbose_name="Copie (F)",
                    ),
                ),
                (
                    "cedules_mention_repertoire",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25"),
                        max_digits=10,
                        verbose_name="Mention répertoire (F)",
                    ),
                ),
                (
                    "cedules_vacation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3000"),
                        max_digits=10,
                        verbose_name="Vacation (F)",
                    ),
                ),
                (
                    "cedules_frais_copie_role",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000"),
                        max_digits=10,
                        verbose_name="Frais copie par rôle (F)",
                    ),
                ),
                (
                    "cedules_tarif_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("140"),
                        max_digits=10,
                        verbose_name="Tarif kilométrique (F/km)",
                    ),
                ),
                (
                    "cedules_seuil_transport",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Seuil transport (km)"
                    ),
                ),
                (
                    "cedules_seuil_mission",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Seuil frais mission (km)"
                    ),
                ),
                (
                    "cedules_mission_1_repas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000"),
                        max_digits=10,
                        verbose_name="Frais mission 1 repas (F)",
                    ),
                ),
                (
                    "cedules_mission_2_repas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20000"),
                        max_digits=10,
                        verbose_name="Frais mission 2 repas (F)",
                    ),
                ),
                (
                    "cedules_mission_journee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("35000"),
                        max_digits=10,
                        verbose_name="Frais mission journée complète (F)",
                    ),
                ),
                (
                    "agenda_heure_debut",
                    models.TimeField(
                        default="08:00", verbose_name="Heure début journée"
                    ),
                ),
                (
                    "agenda_heure_fin",
                    models.TimeField(default="18:00", verbose_name="Heure fin journée"),
                ),
                (
                    "agenda_duree_rdv",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée RDV par défaut (minutes)"
                    ),
                ),
                (
                    "agenda_rappel_jours",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Rappel par défaut (jours avant)"
                    ),
                ),
                (
                    "agenda_rappel_heures",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Rappel par défaut (heures avant)"
                    ),
                ),
                (
                    "agenda_jours_ouvres",
                    models.JSONField(default=list, verbose_name="Jours ouvrés"),
                ),
                (
                    "notif_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Configuration notifications",
                    ),
                ),
                (
                    "smtp_serveur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Serveur SMTP"
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="Port SMTP"),
                ),
                (
                    "smtp_utilisateur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Utilisateur SMTP"
                    ),
                ),
                (
                    "smtp_mot_de_passe",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mot de passe SMTP"
                    ),
                ),
                (
                    "smtp_expediteur",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email expéditeur"
                    ),
                ),
                (
                    "sms_fournisseur",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Fournisseur SMS"
                    ),
                ),
                (
                    "sms_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="API Key SMS"
                    ),
                ),
                (
                    "sms_expediteur",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro expéditeur SMS"
                    ),
                ),
                (
                    "backup_auto",
                    models.BooleanField(
                        default=True, verbose_name="Sauvegardes automatiques"
                    ),
                ),
                (
                    "backup_frequence",
                    models.CharField(
                        choices=[
                            ("quotidienne", "Quotidienne"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuelle", "Mensuelle"),
                        ],
                        default="quotidienne",
                        max_length=20,
                        verbose_name="Fréquence sauvegarde",
                    ),
                ),
                (
                    "backup_heure",
                    models.TimeField(
                        default="02:00", verbose_name="Heure de sauvegarde"
                    ),
                ),
                (
                    "backup_retention",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Conservation sauvegardes (jours)"
                    ),
                ),
                (
                    "backup_emplacement",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("google_drive", "Google Drive"),
                            ("dropbox", "Dropbox"),
                        ],
                        default="local",
                        max_length=20,
                        verbose_name="Emplacement sauvegarde",
                    ),
                ),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[
                            ("clair", "Clair"),
                            ("sombre", "Sombre"),
                            ("auto", "Auto"),
                        ],
                        default="clair",
                        max_length=20,
                        verbose_name="Mode thème",
                    ),
                ),
                (
                    "format_date",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "JJ/MM/AAAA"),
                            ("YYYY-MM-DD", "AAAA-MM-JJ"),
                            ("DD MMMM YYYY", "JJ Mois AAAA"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=20,
                        verbose_name="Format des dates",
                    ),
                ),
                (
                    "separateur_milliers",
                    models.CharField(
                        default=" ", max_length=5, verbose_name="Séparateur milliers"
                    ),
                ),
                (
                    "separateur_decimales",
                    models.CharField(
                        default=",", max_length=5, verbose_name="Séparateur décimales"
                    ),
                ),
                (
                    "dashboard_widgets",
                    models.JSONField(
                        default=list, verbose_name="Widgets tableau de bord"
                    ),
                ),
                (
                    "dashboard_periode",
                    models.CharField(
                        choices=[
                            ("jour", "Jour"),
                            ("semaine", "Semaine"),
                            ("mois", "Mois"),
                        ],
                        default="mois",
                        max_length=20,
                        verbose_name="Période par défaut tableau de bord",
                    ),
                ),
                (
                    "version_app",
                    models.CharField(
                        default="1.0.0",
                        max_length=20,
                        verbose_name="Version application",
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "est_configure",
                    models.BooleanField(
                        default=False, verbose_name="Configuration effectuée"
                    ),
                ),
                (
                    "date_configuration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de configuration"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de l'étude",
                "verbose_name_plural": "Configuration de l'étude",
            },
        ),
        migrations.CreateModel(
            name="JournalModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                ("section", models.CharField(max_length=100, verbose_name="Section")),
                (
                    "champ",
                    models.CharField(max_length=100, verbose_name="Champ modifié"),
                ),
                (
                    "ancienne_valeur",
                    models.TextField(blank=True, verbose_name="Ancienne valeur"),
                ),
                (
                    "nouvelle_valeur",
                    models.TextField(blank=True, verbose_name="Nouvelle valeur"),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modification",
                "verbose_name_plural": "Journal des modifications",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Localite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la localité"),
                ),
                (
                    "departement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Département"
                    ),
                ),
                (
                    "commune",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Commune"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Distance (km)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Localité",
                "verbose_name_plural": "Localités",
                "ordering": ["departement", "nom"],
                "unique_together": {("nom", "commune")},
            },
        ),
        migrations.CreateModel(
            name="ModeleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du modèle")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("actes", "Actes de procédure"),
                            ("factures", "Factures et devis"),
                            ("courriers", "Courriers"),
                            ("baux", "Contrats de bail"),
                            ("etats_lieux", "États des lieux"),
                            ("paie", "Bulletins de paie"),
                            ("memoires", "Mémoires de frais"),
                            ("rapports", "Rapports"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                ("contenu_html", models.TextField(verbose_name="Contenu HTML")),
                (
                    "variables_utilisees",
                    models.JSONField(default=list, verbose_name="Variables utilisées"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parametres_modeles_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de document",
                "verbose_name_plural": "Modèles de documents",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ModeleTypeBail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "modele_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parametres.modeledocument",
                        verbose_name="Modèle de document associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de bail",
                "verbose_name_plural": "Types de baux",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="TauxLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "semestre",
                    models.CharField(
                        choices=[("S1", "Premier semestre"), ("S2", "Second semestre")],
                        max_length=2,
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux (%)"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "source",
                    models.CharField(blank=True, max_length=200, verbose_name="Source"),
                ),
            ],
            options={
                "verbose_name": "Taux légal",
                "verbose_name_plural": "Taux légaux",
                "ordering": ["-annee", "-semestre"],
                "unique_together": {("annee", "semestre")},
            },
        ),
    ]
