# Generated by Django 5.2.8 on 2025-11-29 03:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0002_juridiction_hierarchie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tauxlegal",
            options={
                "ordering": ["-annee"],
                "verbose_name": "Taux d'intérêt légal",
                "verbose_name_plural": "Taux d'intérêt légaux",
            },
        ),
        migrations.AlterUniqueTogether(
            name="tauxlegal",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="configurationetude",
            name="numero_rccm",
            field=models.CharField(
                blank=True,
                help_text="Numéro du Registre du Commerce et du Crédit Mobilier",
                max_length=50,
                null=True,
                verbose_name="Numéro RCCM",
            ),
        ),
        migrations.AddField(
            model_name="configurationetude",
            name="signature_huissier",
            field=models.ImageField(
                blank=True,
                help_text="Image de la signature numérisée (PNG transparent recommandé)",
                null=True,
                upload_to="etude/signatures/",
                verbose_name="Signature de l'huissier",
            ),
        ),
        migrations.AddField(
            model_name="tauxlegal",
            name="date_publication",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date publication JO"
            ),
        ),
        migrations.AddField(
            model_name="tauxlegal",
            name="reference_arrete",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Référence arrêté"
            ),
        ),
        migrations.AlterField(
            model_name="configurationetude",
            name="cedules_mission_1_repas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15000"),
                max_digits=10,
                verbose_name="Frais mission 1 repas (100-149 km)",
            ),
        ),
        migrations.AlterField(
            model_name="configurationetude",
            name="cedules_mission_2_repas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("30000"),
                max_digits=10,
                verbose_name="Frais mission 2 repas (150-199 km)",
            ),
        ),
        migrations.AlterField(
            model_name="configurationetude",
            name="cedules_mission_journee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("45000"),
                max_digits=10,
                verbose_name="Frais mission journée entière (≥200 km)",
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="classe_tpi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("premiere", "Première Classe"),
                    ("deuxieme", "Deuxième Classe"),
                ],
                max_length=20,
                null=True,
                verbose_name="Classe TPI",
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="nom_court",
            field=models.CharField(max_length=100, verbose_name="Nom abrégé"),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="nom_president",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du Président actuel"
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="nom_president_cour",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du Président de la Cour"
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="nom_procureur_general",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du Procureur Général"
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="titre_president",
            field=models.CharField(
                default="Président", max_length=100, verbose_name="Titre du Président"
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="titre_procureur",
            field=models.CharField(
                default="Procureur de la République",
                max_length=100,
                verbose_name="Titre du Procureur",
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="titre_procureur_general",
            field=models.CharField(
                blank=True,
                default="Procureur Général",
                max_length=100,
                verbose_name="Titre du Procureur Général",
            ),
        ),
        migrations.AlterField(
            model_name="juridiction",
            name="type_juridiction",
            field=models.CharField(
                choices=[
                    ("tpi", "Tribunal de Première Instance"),
                    ("cour_appel", "Cour d'Appel"),
                    ("cour_speciale", "Cour Spéciale"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tauxlegal",
            name="annee",
            field=models.PositiveIntegerField(unique=True, verbose_name="Année"),
        ),
        migrations.AlterField(
            model_name="tauxlegal",
            name="taux",
            field=models.DecimalField(
                decimal_places=4, max_digits=6, verbose_name="Taux annuel (%)"
            ),
        ),
        migrations.RemoveField(
            model_name="tauxlegal",
            name="date_debut",
        ),
        migrations.RemoveField(
            model_name="tauxlegal",
            name="date_fin",
        ),
        migrations.RemoveField(
            model_name="tauxlegal",
            name="semestre",
        ),
        migrations.RemoveField(
            model_name="tauxlegal",
            name="source",
        ),
    ]
