# Generated by Django 5.2.8 on 2025-11-29 09:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0003_calendrier_saisie_immo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrancheIPTS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Ordre de la tranche"
                    ),
                ),
                (
                    "montant_min",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Montant minimum (FCFA)",
                    ),
                ),
                (
                    "montant_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Laisser vide pour la dernière tranche (illimité)",
                        max_digits=12,
                        null=True,
                        verbose_name="Montant maximum (FCFA)",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux (%)"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(default="2024-01-01", verbose_name="Date d'effet"),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Tranche IPTS",
                "verbose_name_plural": "Tranches IPTS",
                "ordering": ["ordre"],
            },
        ),
        migrations.AddField(
            model_name="configurationetude",
            name="rh_taux_risques_professionnels",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.0"),
                help_text="Taux accidents du travail (variable selon activité: 1% à 4%)",
                max_digits=5,
                verbose_name="Taux AT/Risques professionnels (%)",
            ),
        ),
        migrations.AddField(
            model_name="configurationetude",
            name="rh_taux_vps",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("4.0"),
                help_text="Versement Patronal sur Salaires",
                max_digits=5,
                verbose_name="Taux VPS (%)",
            ),
        ),
    ]
