# Generated by Django 5.2.8 on 2025-11-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0004_add_hr_parameters_and_ipts_bareme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationEnteteDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            (
                                "etude",
                                "Documents de l'étude (factures, rapports, courriers)",
                            ),
                            ("memoire", "Mémoires et cédules (en-tête juridiction)"),
                            ("acte", "Actes d'huissier"),
                            ("autre", "Autres documents"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "utiliser_entete_image",
                    models.BooleanField(
                        default=False, verbose_name="Utiliser une image d'en-tête"
                    ),
                ),
                (
                    "entete_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploadez votre en-tête habituel (format recommandé : PNG ou JPG, largeur 2480px pour A4)",
                        null=True,
                        upload_to="entetes/",
                        verbose_name="Image d'en-tête",
                    ),
                ),
                (
                    "entete_hauteur",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="Hauteur de la zone d'en-tête sur le document",
                        verbose_name="Hauteur de l'en-tête (pixels)",
                    ),
                ),
                (
                    "entete_marge_haut",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Marge supérieure (pixels)"
                    ),
                ),
                (
                    "entete_marge_gauche",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Marge gauche (pixels)"
                    ),
                ),
                (
                    "entete_marge_droite",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Marge droite (pixels)"
                    ),
                ),
                (
                    "entete_centrer",
                    models.BooleanField(default=True, verbose_name="Centrer l'en-tête"),
                ),
                (
                    "utiliser_pied_image",
                    models.BooleanField(
                        default=False, verbose_name="Utiliser une image de pied de page"
                    ),
                ),
                (
                    "pied_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pieds_page/",
                        verbose_name="Image de pied de page",
                    ),
                ),
                (
                    "pied_hauteur",
                    models.PositiveIntegerField(
                        default=80, verbose_name="Hauteur du pied de page (pixels)"
                    ),
                ),
                (
                    "pied_marge_bas",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Marge inférieure (pixels)"
                    ),
                ),
                (
                    "pied_centrer",
                    models.BooleanField(
                        default=True, verbose_name="Centrer le pied de page"
                    ),
                ),
                (
                    "pied_texte",
                    models.TextField(
                        blank=True,
                        help_text="Ex: Adresse, téléphone, email, RCCM, IFU...",
                        verbose_name="Texte de pied de page (si pas d'image)",
                    ),
                ),
                (
                    "corps_marge_haut",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Espace entre le haut de la page et le début du contenu",
                        verbose_name="Début du contenu (pixels depuis le haut)",
                    ),
                ),
                (
                    "corps_marge_bas",
                    models.PositiveIntegerField(
                        default=100,
                        verbose_name="Fin du contenu (pixels depuis le bas)",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration en-tête document",
                "verbose_name_plural": "Configurations en-têtes documents",
            },
        ),
        migrations.CreateModel(
            name="EnteteJuridiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la juridiction"
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        blank=True,
                        help_text="Ex: COUR D'APPEL DE PARAKOU",
                        max_length=300,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "niveau",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "République (niveau national)"),
                            (2, "Cour Suprême / CRIET"),
                            (3, "Cour d'Appel"),
                            (4, "Tribunal de Première Instance"),
                            (5, "Tribunal de Commerce"),
                            (6, "Autre juridiction"),
                        ],
                        verbose_name="Niveau hiérarchique",
                    ),
                ),
                (
                    "afficher_embleme",
                    models.BooleanField(
                        default=True, verbose_name="Afficher l'emblème national"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="Fraternité - Justice - Travail",
                        max_length=100,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos_juridictions/",
                        verbose_name="Logo spécifique",
                    ),
                ),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "juridiction_superieure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="juridictions_inferieures",
                        to="parametres.entetejuridiction",
                        verbose_name="Juridiction supérieure",
                    ),
                ),
            ],
            options={
                "verbose_name": "En-tête juridiction",
                "verbose_name_plural": "En-têtes juridictions",
                "ordering": ["niveau", "ordre_affichage"],
            },
        ),
    ]
