# Generated by Django 5.2.8 on 2025-11-26 19:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("tarif", models.DecimalField(decimal_places=0, max_digits=10)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Acte de procédure",
                "verbose_name_plural": "Actes de procédure",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="MessageChatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                (
                    "type_message",
                    models.CharField(
                        choices=[("bot", "Bot"), ("user", "Utilisateur")], max_length=10
                    ),
                ),
                ("contenu", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message chatbot",
                "verbose_name_plural": "Messages chatbot",
                "ordering": ["date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Partie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_personne",
                    models.CharField(
                        choices=[
                            ("physique", "Personne physique"),
                            ("morale", "Personne morale"),
                        ],
                        default="physique",
                        max_length=10,
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("prenoms", models.CharField(blank=True, max_length=150)),
                (
                    "nationalite",
                    models.CharField(blank=True, default="Béninoise", max_length=50),
                ),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("domicile", models.TextField(blank=True)),
                ("denomination", models.CharField(blank=True, max_length=200)),
                (
                    "capital_social",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SARL", "SARL"),
                            ("SA", "SA"),
                            ("SAS", "SAS"),
                            ("SNC", "SNC"),
                            ("GIE", "GIE"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                ("siege_social", models.TextField(blank=True)),
                ("representant", models.CharField(blank=True, max_length=150)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "ifu",
                    models.CharField(blank=True, max_length=20, verbose_name="IFU"),
                ),
            ],
            options={
                "verbose_name": "Partie",
                "verbose_name_plural": "Parties",
            },
        ),
        migrations.CreateModel(
            name="TauxLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField(unique=True)),
                ("taux", models.DecimalField(decimal_places=4, max_digits=6)),
                ("source", models.CharField(default="BCEAO", max_length=100)),
            ],
            options={
                "verbose_name": "Taux légal",
                "verbose_name_plural": "Taux légaux",
                "ordering": ["-annee"],
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("huissier", "Huissier"),
                            ("clerc_principal", "Clerc Principal"),
                            ("clerc", "Clerc"),
                            ("secretaire", "Secrétaire"),
                        ],
                        default="clerc",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Collaborateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("huissier", "Huissier"),
                            ("clerc_principal", "Clerc Principal"),
                            ("clerc", "Clerc"),
                            ("secretaire", "Secrétaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("actif", models.BooleanField(default=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaborateur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaborateur",
                "verbose_name_plural": "Collaborateurs",
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=20, unique=True)),
                (
                    "is_contentieux",
                    models.BooleanField(default=False, verbose_name="Contentieux"),
                ),
                (
                    "type_dossier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recouvrement", "Recouvrement"),
                            ("expulsion", "Expulsion"),
                            ("constat", "Constat"),
                            ("signification", "Signification"),
                            ("saisie", "Saisie"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "montant_creance",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                ("date_creance", models.DateField(blank=True, null=True)),
                ("date_ouverture", models.DateField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("urgent", "Urgent"),
                            ("archive", "Archivé"),
                            ("cloture", "Clôturé"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "affecte_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers",
                        to="gestion.collaborateur",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defendeurs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dossiers_defendeur",
                        to="gestion.partie",
                    ),
                ),
                (
                    "demandeurs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dossiers_demandeur",
                        to="gestion.partie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("client", models.CharField(max_length=200)),
                ("montant_ht", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "taux_tva",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=0, max_digits=15)),
                ("montant_ttc", models.DecimalField(decimal_places=0, max_digits=15)),
                ("date_emission", models.DateField(default=django.utils.timezone.now)),
                ("date_echeance", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("attente", "En attente"),
                            ("payee", "Payée"),
                            ("annulee", "Annulée"),
                        ],
                        default="attente",
                        max_length=20,
                    ),
                ),
                (
                    "mecef_qr",
                    models.TextField(blank=True, verbose_name="QR Code MECeF"),
                ),
                (
                    "mecef_numero",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro MECeF"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures",
                        to="gestion.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueCalcul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("complet", "Calcul complet"),
                            ("emoluments", "Émoluments seuls"),
                        ],
                        max_length=20,
                    ),
                ),
                ("donnees", models.JSONField()),
                ("resultats", models.JSONField()),
                ("total", models.DecimalField(decimal_places=0, max_digits=15)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de calcul",
                "verbose_name_plural": "Historiques de calculs",
                "ordering": ["-date_creation"],
            },
        ),
    ]
