# Generated by Django 5.2.8 on 2025-11-26 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du compte")),
                ("banque", models.CharField(max_length=100, verbose_name="Banque")),
                (
                    "numero_compte",
                    models.CharField(max_length=50, verbose_name="Numéro de compte"),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="BIC/SWIFT"
                    ),
                ),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("courant", "Compte courant"),
                            ("epargne", "Compte épargne"),
                            ("sequestre", "Compte séquestre"),
                        ],
                        default="courant",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "solde_actuel",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Compte bancaire",
                "verbose_name_plural": "Comptes bancaires",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="AuditTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("validation", "Validation"),
                            ("approbation", "Approbation"),
                            ("rejet", "Rejet"),
                            ("annulation", "Annulation"),
                            ("ouverture_caisse", "Ouverture de caisse"),
                            ("fermeture_caisse", "Fermeture de caisse"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "entite_type",
                    models.CharField(max_length=50, verbose_name="Type d'entité"),
                ),
                (
                    "entite_id",
                    models.PositiveIntegerField(verbose_name="ID de l'entité"),
                ),
                (
                    "entite_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données avant"
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données après"
                    ),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits_tresorerie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit trésorerie",
                "verbose_name_plural": "Audits trésorerie",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la caisse"),
                ),
                (
                    "site",
                    models.CharField(max_length=200, verbose_name="Site/Localisation"),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "solde_actuel",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde actuel",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("fermee", "Fermée"),
                            ("verification", "En cours de vérification"),
                        ],
                        default="fermee",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Caisse active"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_responsable",
                        to="gestion.collaborateur",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse",
                "verbose_name_plural": "Caisses",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Consignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "montant_initial",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant initial"
                    ),
                ),
                (
                    "montant_reverse",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant déjà reversé",
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant restant"
                    ),
                ),
                ("objet", models.TextField(verbose_name="Objet de la consignation")),
                (
                    "debiteur",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Débiteur (origine des fonds)",
                    ),
                ),
                (
                    "date_reception",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "date_echeance_reversement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date limite de reversement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("partielle", "Partiellement reversée"),
                            ("reversee", "Totalement reversée"),
                            ("bloquee", "Bloquée"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignations",
                        to="gestion.partie",
                        verbose_name="Client (bénéficiaire)",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignations_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignations",
                        to="gestion.dossier",
                        verbose_name="Dossier lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consignation",
                "verbose_name_plural": "Consignations",
                "ordering": ["-date_reception"],
            },
        ),
        migrations.CreateModel(
            name="OperationTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[
                            ("encaissement", "Encaissement"),
                            ("decaissement", "Décaissement"),
                        ],
                        max_length=20,
                        verbose_name="Type d'opération",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(max_length=30, verbose_name="Catégorie"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "date_operation",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date opération"
                    ),
                ),
                (
                    "date_valeur",
                    models.DateField(blank=True, null=True, verbose_name="Date valeur"),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("carte", "Carte bancaire"),
                        ],
                        default="especes",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence paiement (n° chèque, etc.)",
                    ),
                ),
                (
                    "emetteur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Émetteur du paiement"
                    ),
                ),
                (
                    "beneficiaire",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bénéficiaire"
                    ),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif détaillé")),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        upload_to="tresorerie/justificatifs/%Y/%m/",
                        verbose_name="Justificatif",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_attente_approbation", "En attente d'approbation"),
                            ("approuve", "Approuvé"),
                            ("valide", "Validé"),
                            ("paye", "Payé"),
                            ("rejete", "Rejeté"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=25,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "montant_seuil_validation",
                    models.DecimalField(
                        decimal_places=0,
                        default=100000,
                        max_digits=15,
                        verbose_name="Seuil de validation obligatoire",
                    ),
                ),
                (
                    "date_approbation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date approbation"
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                (
                    "date_annulation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date annulation"
                    ),
                ),
                (
                    "motif_annulation",
                    models.TextField(blank=True, verbose_name="Motif d'annulation"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "annule_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_annulees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Annulé par",
                    ),
                ),
                (
                    "approuve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_approuvees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="gestion.caisse",
                        verbose_name="Caisse",
                    ),
                ),
                (
                    "consignation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="gestion.consignation",
                        verbose_name="Consignation liée",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_tresorerie",
                        to="gestion.dossier",
                        verbose_name="Dossier lié",
                    ),
                ),
                (
                    "partie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_tresorerie",
                        to="gestion.partie",
                        verbose_name="Partie concernée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération de trésorerie",
                "verbose_name_plural": "Opérations de trésorerie",
                "ordering": ["-date_operation", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="MouvementConsignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("reception", "Réception de fonds"),
                            ("reversement", "Reversement au client"),
                            ("ajustement", "Ajustement"),
                        ],
                        max_length=20,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mode de paiement"
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "consignation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="gestion.consignation",
                        verbose_name="Consignation",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_consignation_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvement_consignation",
                        to="gestion.operationtresorerie",
                        verbose_name="Opération liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de consignation",
                "verbose_name_plural": "Mouvements de consignation",
                "ordering": ["-date_mouvement", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="RapprochementBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début période")),
                ("date_fin", models.DateField(verbose_name="Date fin période")),
                (
                    "solde_releve",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Solde relevé bancaire",
                    ),
                ),
                (
                    "solde_comptable",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Solde comptable",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Écart",
                    ),
                ),
                (
                    "fichier_releve",
                    models.FileField(
                        blank=True,
                        upload_to="tresorerie/releves/%Y/%m/",
                        verbose_name="Fichier relevé",
                    ),
                ),
                (
                    "format_fichier",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Format (CSV, OFX)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("valide", "Validé"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapprochements",
                        to="gestion.comptebancaire",
                        verbose_name="Compte bancaire",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapprochement bancaire",
                "verbose_name_plural": "Rapprochements bancaires",
                "ordering": ["-date_fin"],
            },
        ),
        migrations.CreateModel(
            name="LigneRapprochement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_releve", models.DateField(verbose_name="Date relevé")),
                (
                    "libelle_releve",
                    models.CharField(max_length=200, verbose_name="Libellé relevé"),
                ),
                (
                    "montant_releve",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant relevé"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_rapproche", "Non rapproché"),
                            ("rapproche", "Rapproché"),
                            ("ecart", "Écart à justifier"),
                        ],
                        default="non_rapproche",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_rapprochement",
                        to="gestion.operationtresorerie",
                        verbose_name="Opération correspondante",
                    ),
                ),
                (
                    "rapprochement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gestion.rapprochementbancaire",
                        verbose_name="Rapprochement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de rapprochement",
                "verbose_name_plural": "Lignes de rapprochement",
                "ordering": ["date_releve"],
            },
        ),
        migrations.CreateModel(
            name="JournalCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date/heure ouverture"
                    ),
                ),
                (
                    "date_fermeture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date/heure fermeture"
                    ),
                ),
                (
                    "solde_ouverture",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde à l'ouverture",
                    ),
                ),
                (
                    "solde_fermeture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Solde à la fermeture",
                    ),
                ),
                (
                    "solde_theorique",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Solde théorique",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Écart constaté",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journaux",
                        to="gestion.caisse",
                        verbose_name="Caisse",
                    ),
                ),
                (
                    "ferme_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_fermees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fermé par",
                    ),
                ),
                (
                    "ouvert_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_ouvertes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ouvert par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de caisse",
                "verbose_name_plural": "Journaux de caisse",
                "ordering": ["-date", "-date_ouverture"],
                "unique_together": {("caisse", "date")},
            },
        ),
    ]
