# Generated by Django 5.2.8 on 2025-11-26 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acteprocedure",
            options={
                "ordering": ["libelle"],
                "verbose_name": "Acte de procedure",
                "verbose_name_plural": "Actes de procedure",
            },
        ),
        migrations.AlterModelOptions(
            name="tauxlegal",
            options={
                "ordering": ["-annee"],
                "verbose_name": "Taux legal",
                "verbose_name_plural": "Taux legaux",
            },
        ),
        migrations.AddField(
            model_name="facture",
            name="date_mecef",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date normalisation MECeF"
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="ifu",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="IFU Client"
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="nim",
            field=models.CharField(blank=True, max_length=20, verbose_name="NIM"),
        ),
        migrations.AddField(
            model_name="facture",
            name="observations",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="collaborateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("huissier", "Huissier"),
                    ("clerc_principal", "Clerc Principal"),
                    ("clerc", "Clerc"),
                    ("secretaire", "Secretaire"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("urgent", "Urgent"),
                    ("archive", "Archive"),
                    ("cloture", "Cloture"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="mecef_numero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero MECeF"
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("attente", "En attente"),
                    ("payee", "Payee"),
                    ("annulee", "Annulee"),
                ],
                default="attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historiquecalcul",
            name="mode",
            field=models.CharField(
                choices=[
                    ("complet", "Calcul complet"),
                    ("emoluments", "Emoluments seuls"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="nationalite",
            field=models.CharField(blank=True, default="Beninoise", max_length=50),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("huissier", "Huissier"),
                    ("clerc_principal", "Clerc Principal"),
                    ("clerc", "Clerc"),
                    ("secretaire", "Secretaire"),
                ],
                default="clerc",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LigneFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantite", models.IntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gestion.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture",
                "verbose_name_plural": "Lignes de facture",
            },
        ),
    ]
