# Generated by Django 5.2.8 on 2025-11-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partie",
            name="enseigne_commerciale",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Enseigne commerciale / Nom commercial",
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="rccm",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="RCCM (Registre du Commerce)"
            ),
        ),
    ]
