# Generated by Django 5.2.8 on 2025-11-27 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion",
            "0002_alter_acteprocedure_options_alter_tauxlegal_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Creancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code créancier"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom/Dénomination"),
                ),
                (
                    "type_creancier",
                    models.CharField(
                        choices=[
                            ("banque", "Banque"),
                            ("microfinance", "Institution de Microfinance"),
                            ("entreprise", "Entreprise"),
                            ("particulier", "Particulier"),
                            ("etat", "État/Administration"),
                            ("autre", "Autre"),
                        ],
                        default="entreprise",
                        max_length=20,
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("site_web", models.URLField(blank=True)),
                (
                    "ifu",
                    models.CharField(blank=True, max_length=20, verbose_name="IFU"),
                ),
                (
                    "rccm",
                    models.CharField(blank=True, max_length=50, verbose_name="RCCM"),
                ),
                (
                    "contact_nom",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom du contact"
                    ),
                ),
                (
                    "contact_fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                ("contact_telephone", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "banque_nom",
                    models.CharField(blank=True, max_length=100, verbose_name="Banque"),
                ),
                (
                    "banque_iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "banque_rib",
                    models.CharField(blank=True, max_length=50, verbose_name="RIB"),
                ),
                (
                    "taux_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Taux de commission (%)",
                    ),
                ),
                (
                    "delai_reversement",
                    models.IntegerField(
                        default=15, verbose_name="Délai de reversement (jours)"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Créancier",
                "verbose_name_plural": "Créanciers",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="date_passage_force",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date passage en phase forcée"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="montant_accessoires",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Accessoires"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="montant_depens",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Dépens"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="montant_emoluments",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Émoluments"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="montant_frais",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Frais de procédure",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="montant_interets",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Intérêts"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="montant_principal",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=15,
                null=True,
                verbose_name="Montant principal",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="phase",
            field=models.CharField(
                choices=[
                    ("amiable", "Phase amiable"),
                    ("force", "Phase forcée (exécution)"),
                ],
                default="amiable",
                max_length=10,
                verbose_name="Phase de recouvrement",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="titre_executoire_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date du titre"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="titre_executoire_juridiction",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Juridiction"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="titre_executoire_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence du titre"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="titre_executoire_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Type de titre exécutoire"
            ),
        ),
        migrations.CreateModel(
            name="BasculementAmiableForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_basculement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("titre_executoire", "Obtention d'un titre exécutoire"),
                            ("echec_amiable", "Échec de la phase amiable"),
                            ("decision_creancier", "Décision du créancier"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "motif_detail",
                    models.TextField(blank=True, verbose_name="Détail du motif"),
                ),
                (
                    "type_titre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type de titre"
                    ),
                ),
                (
                    "reference_titre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence du titre"
                    ),
                ),
                (
                    "juridiction",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Juridiction"
                    ),
                ),
                (
                    "date_titre",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du titre"
                    ),
                ),
                (
                    "montant_principal_restant",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Principal restant",
                    ),
                ),
                (
                    "montant_interets_restant",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Intérêts restants",
                    ),
                ),
                (
                    "montant_frais_restant",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Frais restants",
                    ),
                ),
                (
                    "total_reste_du",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Total restant dû",
                    ),
                ),
                (
                    "depens",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Dépens",
                    ),
                ),
                (
                    "frais_justice",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Frais de justice",
                    ),
                ),
                (
                    "emoluments_ohada",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Émoluments OHADA",
                    ),
                ),
                (
                    "nouveau_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Nouveau total après basculement",
                    ),
                ),
                (
                    "donnees_phase_amiable",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Données de la phase amiable",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basculements",
                        to="gestion.dossier",
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="basculements_effectues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Basculement amiable → forcé",
                "verbose_name_plural": "Basculements amiable → forcé",
                "ordering": ["-date_basculement"],
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="creancier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dossiers",
                to="gestion.creancier",
                verbose_name="Créancier",
            ),
        ),
        migrations.CreateModel(
            name="Encaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "date_encaissement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'encaissement",
                    ),
                ),
                (
                    "date_valeur",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de valeur"
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("carte", "Carte bancaire"),
                            ("compensation", "Compensation"),
                            ("autre", "Autre"),
                        ],
                        default="especes",
                        max_length=20,
                    ),
                ),
                (
                    "payeur_nom",
                    models.CharField(max_length=200, verbose_name="Nom du payeur"),
                ),
                ("payeur_telephone", models.CharField(blank=True, max_length=50)),
                (
                    "payeur_qualite",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Débiteur, Mandataire, Caution, etc.",
                        max_length=100,
                        verbose_name="Qualité du payeur",
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True,
                        help_text="N° de chèque, référence virement, etc.",
                        max_length=100,
                        verbose_name="Référence du paiement",
                    ),
                ),
                ("banque_emettrice", models.CharField(blank=True, max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("annule", "Annulé"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "cumul_encaisse_avant",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Cumul encaissé avant cet encaissement",
                    ),
                ),
                (
                    "cumul_encaisse_apres",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Cumul encaissé après cet encaissement",
                    ),
                ),
                (
                    "solde_restant",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Solde restant dû",
                    ),
                ),
                (
                    "montant_a_reverser",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant à reverser au créancier",
                    ),
                ),
                (
                    "reversement_statut",
                    models.CharField(
                        choices=[("en_attente", "En attente"), ("reverse", "Reversé")],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut reversement",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "piece_justificative",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="encaissements/",
                        verbose_name="Pièce justificative",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaissements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaissements",
                        to="gestion.dossier",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaissements_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaissement",
                "verbose_name_plural": "Encaissements",
                "ordering": ["-date_encaissement", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="EnvoiAutomatiquePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("bimensuel", "Bimensuel"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                        ],
                        default="mensuel",
                        max_length=20,
                    ),
                ),
                (
                    "jour_envoi",
                    models.IntegerField(
                        default=1,
                        help_text="Jour du mois (1-28) ou jour de la semaine (1-7 pour hebdomadaire)",
                        verbose_name="Jour d'envoi",
                    ),
                ),
                (
                    "heure_envoi",
                    models.TimeField(default="08:00", verbose_name="Heure d'envoi"),
                ),
                (
                    "destinataires",
                    models.JSONField(
                        default=list, verbose_name="Adresses email destinataires"
                    ),
                ),
                (
                    "copie_gestionnaire",
                    models.BooleanField(
                        default=True, verbose_name="Envoyer copie au gestionnaire"
                    ),
                ),
                (
                    "filtres_point",
                    models.JSONField(blank=True, default=dict, verbose_name="Filtres"),
                ),
                ("actif", models.BooleanField(default=True)),
                ("dernier_envoi", models.DateTimeField(blank=True, null=True)),
                ("prochain_envoi", models.DateTimeField(blank=True, null=True)),
                ("nb_envois_total", models.IntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "creancier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envois_automatiques",
                        to="gestion.creancier",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envois_auto_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Envoi automatique de point",
                "verbose_name_plural": "Envois automatiques de points",
                "ordering": ["creancier", "frequence"],
            },
        ),
        migrations.CreateModel(
            name="ImputationEncaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_imputation",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("interets", "Intérêts"),
                            ("interets_retard", "Intérêts de retard"),
                            ("frais", "Frais de procédure"),
                            ("emoluments", "Émoluments"),
                            ("debours", "Débours"),
                            ("depens", "Dépens"),
                            ("accessoires", "Accessoires"),
                            ("autres", "Autres"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "solde_avant",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "solde_apres",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("observations", models.CharField(blank=True, max_length=500)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "encaissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imputations",
                        to="gestion.encaissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imputation d'encaissement",
                "verbose_name_plural": "Imputations d'encaissements",
                "ordering": ["encaissement", "type_imputation"],
            },
        ),
        migrations.CreateModel(
            name="PointGlobalCreancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("periode_debut", models.DateField(verbose_name="Début de période")),
                ("periode_fin", models.DateField(verbose_name="Fin de période")),
                (
                    "filtres",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Filtres appliqués"
                    ),
                ),
                ("nb_dossiers_total", models.IntegerField(default=0)),
                ("nb_dossiers_actifs", models.IntegerField(default=0)),
                ("nb_dossiers_clotures", models.IntegerField(default=0)),
                (
                    "montant_total_creances",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "montant_total_encaisse",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "montant_total_reverse",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "montant_reste_a_encaisser",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "montant_reste_a_reverser",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "taux_recouvrement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "donnees_detaillees",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Données détaillées du point",
                    ),
                ),
                (
                    "document_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="points_creanciers/",
                        verbose_name="Document PDF",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "creancier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_globaux",
                        to="gestion.creancier",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_generes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point global créancier",
                "verbose_name_plural": "Points globaux créanciers",
                "ordering": ["-date_generation"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueEnvoiPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_envoi", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("succes", "Succès"),
                            ("echec", "Échec"),
                            ("partiel", "Partiel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("destinataires_envoyes", models.JSONField(default=list)),
                ("destinataires_echec", models.JSONField(default=list)),
                ("message_erreur", models.TextField(blank=True)),
                (
                    "envoi_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="gestion.envoiautomatiquepoint",
                    ),
                ),
                (
                    "point_global",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envois",
                        to="gestion.pointglobalcreancier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'envoi de point",
                "verbose_name_plural": "Historiques d'envois de points",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="PortefeuilleCreancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut_relation",
                    models.DateField(verbose_name="Date début de relation"),
                ),
                (
                    "parametres",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Paramètres personnalisés",
                    ),
                ),
                ("nb_dossiers_actifs", models.IntegerField(default=0)),
                (
                    "montant_total_creances",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "montant_total_encaisse",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "montant_total_reverse",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                (
                    "taux_recouvrement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("derniere_maj_stats", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "creancier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portefeuille",
                        to="gestion.creancier",
                    ),
                ),
                (
                    "gestionnaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portefeuilles_geres",
                        to="gestion.collaborateur",
                        verbose_name="Gestionnaire référent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille créancier",
                "verbose_name_plural": "Portefeuilles créanciers",
            },
        ),
        migrations.CreateModel(
            name="Reversement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Référence"
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "date_reversement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de reversement"
                    ),
                ),
                (
                    "mode_reversement",
                    models.CharField(
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("especes", "Espèces"),
                            ("autre", "Autre"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                (
                    "reference_virement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence virement"
                    ),
                ),
                (
                    "numero_cheque",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de chèque"
                    ),
                ),
                (
                    "banque",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Banque émettrice"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de reversement"),
                            ("en_cours", "En cours"),
                            ("effectue", "Effectué"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "preuve_reversement",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reversements/",
                        verbose_name="Preuve de reversement",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "creancier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversements",
                        to="gestion.creancier",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversements_effectues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encaissements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reversements",
                        to="gestion.encaissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversement",
                "verbose_name_plural": "Reversements",
                "ordering": ["-date_creation"],
            },
        ),
    ]
