# Generated by Django 5.2.8 on 2025-11-28 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_memoires_cedules_hierarchique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex: dossiers.creer, tresorerie.voir",
                        max_length=100,
                        unique=True,
                        verbose_name="Code permission",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la permission"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("dossiers", "Dossiers"),
                            ("facturation", "Facturation"),
                            ("tresorerie", "Trésorerie"),
                            ("comptabilite", "Comptabilité"),
                            ("recouvrement", "Recouvrement"),
                            ("gerance", "Gérance Immobilière"),
                            ("rh", "Ressources Humaines"),
                            ("agenda", "Agenda"),
                            ("memoires", "Mémoires Cédules"),
                            ("parametres", "Paramètres"),
                            ("securite", "Sécurité"),
                        ],
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code du rôle"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du rôle")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "est_systeme",
                    models.BooleanField(
                        default=False,
                        help_text="Les rôles système ne peuvent pas être supprimés",
                        verbose_name="Rôle système",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="AdresseIPAutorisee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ips_ajoutees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse IP autorisée",
                "verbose_name_plural": "Adresses IP autorisées",
                "ordering": ["adresse_ip"],
            },
        ),
        migrations.CreateModel(
            name="AdresseIPBloquee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("raison", models.TextField(verbose_name="Raison du blocage")),
                ("active", models.BooleanField(default=True)),
                ("date_blocage", models.DateTimeField(auto_now_add=True)),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laisser vide pour un blocage permanent",
                        null=True,
                        verbose_name="Date d'expiration",
                    ),
                ),
                (
                    "bloque_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ips_bloquees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse IP bloquée",
                "verbose_name_plural": "Adresses IP bloquées",
                "ordering": ["-date_blocage"],
            },
        ),
        migrations.CreateModel(
            name="AlerteSecurite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_heure",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("echec_connexion", "Échec de connexion répété"),
                            ("nouvelle_ip", "Connexion depuis nouvelle IP"),
                            ("hors_horaires", "Connexion hors horaires"),
                            ("acces_refuse", "Tentative d'accès non autorisé"),
                            ("export_massif", "Export massif de données"),
                            ("modif_securite", "Modification paramètres sécurité"),
                            ("utilisateur_cree", "Création utilisateur"),
                            ("utilisateur_supprime", "Suppression utilisateur"),
                            ("mdp_admin_change", "Changement mot de passe admin"),
                            ("session_suspecte", "Session suspecte"),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("critical", "Critique"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Gravité",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("utilisateur_nom", models.CharField(blank=True, max_length=200)),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "donnees_supplementaires",
                    models.JSONField(blank=True, null=True, verbose_name="Données"),
                ),
                ("traitee", models.BooleanField(default=False, verbose_name="Traitée")),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "commentaire_traitement",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur_concerne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_securite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de sécurité",
                "verbose_name_plural": "Alertes de sécurité",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="CleRecuperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle_hash",
                    models.CharField(max_length=255, verbose_name="Hash de la clé"),
                ),
                ("active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_utilisation", models.DateTimeField(blank=True, null=True)),
                (
                    "utilisee_par_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "creee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cles_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé de récupération",
                "verbose_name_plural": "Clés de récupération",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueMdpUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mdp_hash", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_mdp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique mot de passe",
                "verbose_name_plural": "Historiques mots de passe",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PolitiqueSecurite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mdp_longueur_min",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Longueur minimale MDP"
                    ),
                ),
                (
                    "mdp_exiger_majuscule",
                    models.BooleanField(default=True, verbose_name="Exiger majuscule"),
                ),
                (
                    "mdp_exiger_minuscule",
                    models.BooleanField(default=True, verbose_name="Exiger minuscule"),
                ),
                (
                    "mdp_exiger_chiffre",
                    models.BooleanField(default=True, verbose_name="Exiger chiffre"),
                ),
                (
                    "mdp_exiger_special",
                    models.BooleanField(
                        default=False, verbose_name="Exiger caractère spécial"
                    ),
                ),
                (
                    "mdp_expiration_jours",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="0 = jamais",
                        verbose_name="Expiration MDP (jours)",
                    ),
                ),
                (
                    "mdp_historique",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Empêche la réutilisation des X derniers mots de passe",
                        verbose_name="Historique MDP",
                    ),
                ),
                (
                    "mdp_tentatives_blocage",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Tentatives avant blocage"
                    ),
                ),
                (
                    "mdp_duree_blocage",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="0 = déblocage manuel",
                        verbose_name="Durée de blocage (minutes)",
                    ),
                ),
                (
                    "session_duree_heures",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="Durée de session (heures)"
                    ),
                ),
                (
                    "session_inactivite_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        verbose_name="Déconnexion après inactivité (minutes)",
                    ),
                ),
                (
                    "session_simultanees",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Sessions simultanées autorisées"
                    ),
                ),
                (
                    "session_forcer_deconnexion",
                    models.BooleanField(
                        default=True,
                        verbose_name="Forcer déconnexion si nouvelle session",
                    ),
                ),
                (
                    "session_multi_appareils",
                    models.BooleanField(
                        default=False, verbose_name="Autoriser plusieurs appareils"
                    ),
                ),
                (
                    "mode_2fa",
                    models.CharField(
                        choices=[
                            ("desactive", "Désactivée"),
                            ("optionnel", "Optionnelle"),
                            ("obligatoire_tous", "Obligatoire pour tous"),
                            ("obligatoire_admin", "Obligatoire pour administrateurs"),
                        ],
                        default="optionnel",
                        max_length=20,
                        verbose_name="Authentification à deux facteurs",
                    ),
                ),
                (
                    "restriction_ip_active",
                    models.BooleanField(
                        default=False, verbose_name="Restriction par IP activée"
                    ),
                ),
                (
                    "restriction_horaires_active",
                    models.BooleanField(
                        default=False, verbose_name="Restriction horaires activée"
                    ),
                ),
                (
                    "horaire_debut",
                    models.TimeField(
                        default="06:00", verbose_name="Heure début autorisée"
                    ),
                ),
                (
                    "horaire_fin",
                    models.TimeField(
                        default="22:00", verbose_name="Heure fin autorisée"
                    ),
                ),
                (
                    "jours_autorises",
                    models.JSONField(
                        default=list,
                        help_text="Liste des jours (1=Lundi, 7=Dimanche)",
                        verbose_name="Jours autorisés",
                    ),
                ),
                (
                    "audit_conservation_jours",
                    models.PositiveSmallIntegerField(
                        default=365, verbose_name="Conservation des logs (jours)"
                    ),
                ),
                (
                    "audit_archive_auto",
                    models.BooleanField(
                        default=True, verbose_name="Archivage automatique"
                    ),
                ),
                (
                    "audit_export_periodique",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="mensuel",
                        max_length=20,
                        verbose_name="Export périodique",
                    ),
                ),
                (
                    "alerte_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Email de notification des alertes",
                    ),
                ),
                ("alerte_echec_connexion", models.BooleanField(default=True)),
                ("alerte_nouvelle_ip", models.BooleanField(default=True)),
                ("alerte_hors_horaires", models.BooleanField(default=True)),
                ("alerte_acces_refuse", models.BooleanField(default=True)),
                ("alerte_export_massif", models.BooleanField(default=True)),
                ("alerte_modif_securite", models.BooleanField(default=True)),
                ("alerte_utilisateur_cree", models.BooleanField(default=True)),
                ("alerte_mdp_admin", models.BooleanField(default=True)),
                (
                    "maintenance_active",
                    models.BooleanField(default=False, verbose_name="Mode maintenance"),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="L'application est temporairement indisponible pour maintenance.",
                        verbose_name="Message de maintenance",
                    ),
                ),
                (
                    "maintenance_admin_autorise",
                    models.BooleanField(
                        default=True, verbose_name="Autoriser admin pendant maintenance"
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="politiques_modifiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Politique de sécurité",
                "verbose_name_plural": "Politique de sécurité",
            },
        ),
        migrations.CreateModel(
            name="SessionUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="Navigateur/Agent"),
                ),
                ("navigateur", models.CharField(blank=True, max_length=100)),
                (
                    "systeme_os",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Système d'exploitation",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de connexion"
                    ),
                ),
                (
                    "date_derniere_activite",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "module_actuel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Module actuel"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_securite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateurs",
                "ordering": ["-date_derniere_activite"],
            },
        ),
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_heure",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
                ),
                (
                    "utilisateur_nom",
                    models.CharField(
                        blank=True,
                        help_text="Sauvegardé en cas de suppression de l'utilisateur",
                        max_length=200,
                        verbose_name="Nom utilisateur",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("connexion", "Connexion"),
                            ("deconnexion", "Déconnexion"),
                            ("echec_connexion", "Échec de connexion"),
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("suppression", "Suppression"),
                            ("consultation", "Consultation"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("approbation", "Approbation"),
                            ("rejet", "Rejet"),
                            ("changement_mdp", "Changement de mot de passe"),
                            ("reset_mdp", "Réinitialisation de mot de passe"),
                            ("acces_refuse", "Accès refusé"),
                            ("parametrage", "Modification paramètres"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("connexion", "Connexion"),
                            ("dossiers", "Dossiers"),
                            ("facturation", "Facturation"),
                            ("tresorerie", "Trésorerie"),
                            ("comptabilite", "Comptabilité"),
                            ("recouvrement", "Recouvrement"),
                            ("gerance", "Gérance"),
                            ("rh", "Ressources Humaines"),
                            ("agenda", "Agenda"),
                            ("memoires", "Mémoires"),
                            ("parametres", "Paramètres"),
                            ("securite", "Sécurité"),
                            ("systeme", "Système"),
                        ],
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données avant"
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données après"
                    ),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="Navigateur")),
                (
                    "objet_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type d'objet"
                    ),
                ),
                (
                    "objet_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de l'objet"
                    ),
                ),
                (
                    "objet_representation",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Représentation"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée du journal d'audit",
                "verbose_name_plural": "Journal d'audit",
                "ordering": ["-date_heure"],
                "indexes": [
                    models.Index(
                        fields=["date_heure"], name="gestion_jou_date_he_77b4fd_idx"
                    ),
                    models.Index(
                        fields=["utilisateur"], name="gestion_jou_utilisa_350f97_idx"
                    ),
                    models.Index(
                        fields=["action"], name="gestion_jou_action_1dfde9_idx"
                    ),
                    models.Index(
                        fields=["module"], name="gestion_jou_module_ce242a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autorise",
                    models.BooleanField(
                        default=True,
                        help_text="True pour accorder, False pour refuser (surcharge le rôle)",
                        verbose_name="Autorisé",
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_modifiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisateurs_permission",
                        to="gestion.permission",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_personnalisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission utilisateur",
                "verbose_name_plural": "Permissions utilisateurs",
                "unique_together": {("utilisateur", "permission")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_permission",
                        to="gestion.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_role",
                        to="gestion.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission du rôle",
                "verbose_name_plural": "Permissions des rôles",
                "unique_together": {("role", "permission")},
            },
        ),
    ]
