# Generated by Django 5.2.8 on 2025-11-29 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0006_memoire_juridiction"),
        ("parametres", "0003_calendrier_saisie_immo"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoire",
            name="date_paiement",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de paiement"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="date_taxation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date taxation Président"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="date_transmission_tresor",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date transmission Trésor"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="date_visa",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date visa Procureur"
            ),
        ),
        migrations.AlterField(
            model_name="destinataireaffaire",
            name="frais_mission",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="15 000 (1 repas) / 30 000 (2 repas) / 45 000 F (journée) - UNE SEULE FOIS",
                max_digits=15,
                verbose_name="Frais de mission",
            ),
        ),
        migrations.AlterField(
            model_name="destinataireaffaire",
            name="type_mission",
            field=models.CharField(
                choices=[
                    ("aucune", "Aucune mission"),
                    ("1_repas", "1 repas (distance 100-149 km)"),
                    ("2_repas", "2 repas (distance 150-199 km)"),
                    ("journee_complete", "Journée entière (distance ≥ 200 km)"),
                ],
                default="aucune",
                max_length=30,
                verbose_name="Type de mission",
            ),
        ),
        migrations.AlterField(
            model_name="memoire",
            name="juridiction",
            field=models.ForeignKey(
                blank=True,
                help_text="Juridiction pour génération des signatures Réquisition/Exécutoire",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memoires",
                to="parametres.juridiction",
                verbose_name="Juridiction requérante",
            ),
        ),
        migrations.AlterField(
            model_name="memoire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("en_cours", "En cours de rédaction"),
                    ("a_verifier", "À vérifier"),
                    ("certifie", "Certifié par l'huissier"),
                    ("soumis", "Soumis au Parquet"),
                    ("vise", "Visé par le Procureur"),
                    ("taxe", "Taxé par le Président"),
                    ("en_paiement", "Transmis au Trésor"),
                    ("paye", "Payé"),
                    ("rejete", "Rejeté"),
                ],
                default="brouillon",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CalendrierSaisieImmo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "creancier",
                    models.CharField(
                        max_length=500, verbose_name="Créancier poursuivant"
                    ),
                ),
                ("debiteurs", models.TextField(verbose_name="Débiteur(s) saisi(s)")),
                (
                    "juridiction",
                    models.CharField(
                        default="Tribunal de Première Instance de Première Classe de Parakou",
                        max_length=200,
                    ),
                ),
                (
                    "designation_immeuble",
                    models.TextField(verbose_name="Désignation de l'immeuble"),
                ),
                (
                    "titre_foncier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° Titre foncier"
                    ),
                ),
                (
                    "date_commandement",
                    models.DateField(verbose_name="Date signification commandement"),
                ),
                ("date_publication", models.DateField(blank=True, null=True)),
                ("date_depot_cahier", models.DateField(blank=True, null=True)),
                ("date_sommation", models.DateField(blank=True, null=True)),
                ("date_audience_eventuelle", models.DateField(blank=True, null=True)),
                ("date_adjudication", models.DateField(blank=True, null=True)),
                ("date_publication_reelle", models.DateField(blank=True, null=True)),
                ("date_depot_cahier_reel", models.DateField(blank=True, null=True)),
                ("date_sommation_reelle", models.DateField(blank=True, null=True)),
                ("date_audience_reelle", models.DateField(blank=True, null=True)),
                ("date_adjudication_reelle", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "document_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="calendriers_saisie_immo/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendriers_saisie_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendriers_saisie_immo",
                        to="gestion.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendrier saisie immobilière",
                "verbose_name_plural": "Calendriers saisies immobilières",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistreParquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_affaire",
                    models.CharField(max_length=100, verbose_name="Référence affaire"),
                ),
                (
                    "nature_diligence",
                    models.CharField(
                        max_length=200, verbose_name="Nature de la diligence"
                    ),
                ),
                (
                    "date_diligence",
                    models.DateField(verbose_name="Date de la diligence"),
                ),
                (
                    "montant_emoluments",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant des émoluments",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "acte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrees_registre",
                        to="gestion.actedestinataire",
                        verbose_name="Acte lié",
                    ),
                ),
                (
                    "memoire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registre_parquet",
                        to="gestion.memoire",
                        verbose_name="Mémoire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée registre Parquet",
                "verbose_name_plural": "Registre Parquet",
                "ordering": ["-date_diligence", "-date_creation"],
            },
        ),
    ]
