# Generated by Django 5.2.8 on 2025-11-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_calendrier_saisie_immo"),
    ]

    operations = [
        migrations.AddField(
            model_name="creancier",
            name="capital_social",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=15,
                null=True,
                verbose_name="Capital social (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="creancier",
            name="forme_juridique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SARL", "SARL - Société à Responsabilité Limitée"),
                    ("SARLU", "SARLU - SARL Unipersonnelle"),
                    ("SA", "SA - Société Anonyme"),
                    ("SAS", "SAS - Société par Actions Simplifiée"),
                    ("SASU", "SASU - SAS Unipersonnelle"),
                    ("SNC", "SNC - Société en Nom Collectif"),
                    ("SCS", "SCS - Société en Commandite Simple"),
                    ("GIE", "GIE - Groupement d'Intérêt Économique"),
                    ("ASSOCIATION", "Association"),
                    ("ONG", "ONG"),
                    ("ETABLISSEMENT_PUBLIC", "Établissement public"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AddField(
            model_name="creancier",
            name="qualite_representant",
            field=models.CharField(
                blank=True,
                help_text="Ex: Gérant, Directeur Général, PDG",
                max_length=100,
                verbose_name="Qualité du représentant",
            ),
        ),
        migrations.AddField(
            model_name="creancier",
            name="representant_legal",
            field=models.CharField(
                blank=True,
                help_text="Nom complet du gérant/directeur",
                max_length=200,
                verbose_name="Représentant légal",
            ),
        ),
        migrations.AddField(
            model_name="creancier",
            name="siege_social",
            field=models.TextField(
                blank=True,
                help_text="Adresse complète du siège social",
                verbose_name="Siège social",
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="qualite_representant",
            field=models.CharField(
                blank=True,
                help_text="Ex: Gérant, Directeur Général, PDG",
                max_length=100,
                verbose_name="Qualité du représentant",
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="rccm",
            field=models.CharField(
                blank=True,
                help_text="Ex: RB/COT/21 B 12345",
                max_length=100,
                verbose_name="N° RCCM",
            ),
        ),
        migrations.AlterField(
            model_name="creancier",
            name="ifu",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Fiscal Unique",
                max_length=50,
                verbose_name="N° IFU",
            ),
        ),
        migrations.AlterField(
            model_name="creancier",
            name="rccm",
            field=models.CharField(
                blank=True,
                help_text="Ex: RB/COT/21 B 12345",
                max_length=100,
                verbose_name="N° RCCM",
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="capital_social",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=15,
                null=True,
                verbose_name="Capital social (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="denomination",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dénomination sociale"
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="forme_juridique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SARL", "SARL - Société à Responsabilité Limitée"),
                    ("SARLU", "SARLU - SARL Unipersonnelle"),
                    ("SA", "SA - Société Anonyme"),
                    ("SAS", "SAS - Société par Actions Simplifiée"),
                    ("SASU", "SASU - SAS Unipersonnelle"),
                    ("SNC", "SNC - Société en Nom Collectif"),
                    ("SCS", "SCS - Société en Commandite Simple"),
                    ("GIE", "GIE - Groupement d'Intérêt Économique"),
                    ("ASSOCIATION", "Association"),
                    ("ONG", "ONG"),
                    ("ETABLISSEMENT_PUBLIC", "Établissement public"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="ifu",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Fiscal Unique",
                max_length=50,
                verbose_name="N° IFU",
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="representant",
            field=models.CharField(
                blank=True,
                help_text="Nom complet du gérant/directeur",
                max_length=150,
                verbose_name="Représentant légal",
            ),
        ),
        migrations.AlterField(
            model_name="partie",
            name="siege_social",
            field=models.TextField(
                blank=True,
                help_text="Adresse complète du siège",
                verbose_name="Siège social",
            ),
        ),
    ]
