# Generated by Django 5.2.8 on 2025-11-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_add_legal_entity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="partie",
            name="activite_commerciale",
            field=models.CharField(
                blank=True,
                help_text="Ex: Commerce général, Import-Export",
                max_length=300,
                verbose_name="Activité commerciale",
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="enseigne",
            field=models.CharField(
                blank=True,
                help_text="Ex: SUPERMARCHÉ DU CENTRE",
                max_length=200,
                verbose_name="Enseigne",
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="est_commercant",
            field=models.BooleanField(
                default=False, verbose_name="Est commerçant/entrepreneur individuel"
            ),
        ),
        migrations.AddField(
            model_name="partie",
            name="nom_commercial",
            field=models.CharField(
                blank=True,
                help_text="Ex: KOFFI DISTRIBUTION",
                max_length=200,
                verbose_name="Nom commercial",
            ),
        ),
    ]
