# Generated by Django 5.2.8 on 2025-11-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0009_add_commercant_fields_personne_physique"),
        ("tresorerie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encaissement",
            name="compte_tresorerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encaissements",
                to="tresorerie.comptebancaire",
                verbose_name="Compte de trésorerie",
            ),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="mouvement_tresorerie",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encaissement_source",
                to="tresorerie.mouvementtresorerie",
                verbose_name="Mouvement de trésorerie",
            ),
        ),
    ]
