# Generated by Django 5.2.8 on 2025-11-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0010_encaissement_compte_tresorerie_and_more"),
        ("tresorerie", "0002_remove_mouvementtresorerie_dossier_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reversement",
            name="compte_tresorerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversements",
                to="tresorerie.comptebancaire",
                verbose_name="Compte de trésorerie",
            ),
        ),
        migrations.AddField(
            model_name="reversement",
            name="mouvement_tresorerie",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversement_source",
                to="tresorerie.mouvementtresorerie",
                verbose_name="Mouvement de trésorerie",
            ),
        ),
    ]
