# Generated by Django 5.2.8 on 2025-11-29 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_reversement_compte_tresorerie_and_more"),
        ("tresorerie", "0002_remove_mouvementtresorerie_dossier_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementGlobalMemoires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence paiement"
                    ),
                ),
                (
                    "juridiction",
                    models.CharField(
                        choices=[
                            ("ca_parakou", "Cour d'Appel de Parakou"),
                            ("ca_cotonou", "Cour d'Appel de Cotonou"),
                            ("ca_abomey", "Cour d'Appel d'Abomey"),
                            ("criet", "CRIET"),
                            ("cour_supreme", "Cour Suprême"),
                            ("autre", "Autre juridiction"),
                        ],
                        max_length=50,
                        verbose_name="Juridiction payeuse",
                    ),
                ),
                (
                    "comptable_public",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nom du Comptable Public",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Montant reçu"
                    ),
                ),
                ("date_paiement", models.DateField(verbose_name="Date du paiement")),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mode de paiement"
                    ),
                ),
                (
                    "reference_virement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence virement/chèque",
                    ),
                ),
                (
                    "periode_debut",
                    models.DateField(blank=True, null=True, verbose_name="Période du"),
                ),
                (
                    "periode_fin",
                    models.DateField(blank=True, null=True, verbose_name="Période au"),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compte_tresorerie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements_memoires",
                        to="tresorerie.comptebancaire",
                        verbose_name="Compte crédité",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_memoires_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facture_mecef",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_memoires",
                        to="gestion.facture",
                        verbose_name="Facture MECeF associée",
                    ),
                ),
                (
                    "memoires_concernes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Association indicative, le paiement n'est pas rattaché à un mémoire spécifique",
                        related_name="paiements_recus",
                        to="gestion.memoire",
                        verbose_name="Mémoires concernés (indicatif)",
                    ),
                ),
                (
                    "mouvement_tresorerie",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiement_memoires_source",
                        to="tresorerie.mouvementtresorerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement global mémoires",
                "verbose_name_plural": "Paiements globaux mémoires",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
