# Generated by Django 5.2.8 on 2025-11-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0012_add_paiement_global_memoires"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoire",
            name="autorite_controle",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Autorité de contrôle"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="date_controle",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date du contrôle"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="date_rejet",
            field=models.DateField(blank=True, null=True, verbose_name="Date du rejet"),
        ),
        migrations.AddField(
            model_name="memoire",
            name="date_soumission",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de soumission"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="est_correctif",
            field=models.BooleanField(
                default=False, verbose_name="Est un mémoire correctif"
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="memoire_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memoires_correctifs",
                to="gestion.memoire",
                verbose_name="Mémoire original (si correctif)",
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="montant_corrige",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Montant demandé par l'autorité si correction requise",
                max_digits=12,
                null=True,
                verbose_name="Montant corrigé demandé",
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="motif_rejet",
            field=models.TextField(blank=True, verbose_name="Motif du rejet"),
        ),
        migrations.AddField(
            model_name="memoire",
            name="statut_validation",
            field=models.CharField(
                choices=[
                    ("soumis", "Soumis"),
                    ("en_attente", "En attente de contrôle"),
                    ("valide", "Validé"),
                    ("rejete_correction", "Rejeté - Correction demandée"),
                    ("rejete_definitif", "Rejeté définitivement"),
                    ("paye", "Payé"),
                ],
                default="soumis",
                max_length=30,
                verbose_name="Statut de validation",
            ),
        ),
        migrations.CreateModel(
            name="HistoriqueValidationMemoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("soumission", "Soumission"),
                            ("validation", "Validation"),
                            ("rejet_correction", "Rejet avec demande de correction"),
                            ("rejet_definitif", "Rejet définitif"),
                            ("correction", "Correction effectuée"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                (
                    "effectue_par",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Effectué par"
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "montant_avant",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=12, null=True
                    ),
                ),
                (
                    "montant_apres",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=12, null=True
                    ),
                ),
                (
                    "memoire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_validations",
                        to="gestion.memoire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique validation mémoire",
                "verbose_name_plural": "Historiques validation mémoires",
                "ordering": ["-date_action"],
            },
        ),
    ]
