# Generated by Django 5.2.8 on 2025-11-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0013_memoire_autorite_controle_memoire_date_controle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="avoir_lie",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facture_annulee",
                to="gestion.facture",
                verbose_name="Avoir d'annulation",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="facture_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Facture originale annulée (pour avoir) ou corrigée (pour corrective)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factures_liees",
                to="gestion.facture",
                verbose_name="Facture d'origine",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="motif_avoir_correction",
            field=models.TextField(
                blank=True,
                help_text="Raison de l'annulation ou de la correction",
                verbose_name="Motif de l'avoir/correction",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="statut_mecef",
            field=models.CharField(
                choices=[
                    ("non_normalise", "Non normalisé"),
                    ("en_attente", "En attente de normalisation"),
                    ("normalise", "Normalisé"),
                    ("erreur", "Erreur de normalisation"),
                    ("annule", "Annulé par avoir"),
                ],
                default="non_normalise",
                max_length=20,
                verbose_name="Statut MECeF",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="type_facture",
            field=models.CharField(
                choices=[
                    ("standard", "Facture standard"),
                    ("avoir", "Facture d'avoir (annulation)"),
                    ("corrective", "Facture corrective"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Type de facture",
            ),
        ),
    ]
