# Generated by Django 5.2.8 on 2025-11-29 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0014_facture_avoir_lie_facture_facture_origine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionsGranulaires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dossiers_voir",
                    models.BooleanField(default=True, verbose_name="Voir les dossiers"),
                ),
                (
                    "dossiers_creer",
                    models.BooleanField(
                        default=False, verbose_name="Créer des dossiers"
                    ),
                ),
                (
                    "dossiers_modifier",
                    models.BooleanField(
                        default=False, verbose_name="Modifier les dossiers"
                    ),
                ),
                (
                    "dossiers_supprimer",
                    models.BooleanField(
                        default=False, verbose_name="Supprimer des dossiers"
                    ),
                ),
                (
                    "dossiers_voir_tous",
                    models.BooleanField(
                        default=False,
                        verbose_name="Voir TOUS les dossiers (sinon uniquement les siens)",
                    ),
                ),
                (
                    "recouvrement_voir",
                    models.BooleanField(
                        default=True, verbose_name="Voir les recouvrements"
                    ),
                ),
                (
                    "recouvrement_creer",
                    models.BooleanField(
                        default=False, verbose_name="Créer des recouvrements"
                    ),
                ),
                (
                    "recouvrement_modifier",
                    models.BooleanField(
                        default=False, verbose_name="Modifier les recouvrements"
                    ),
                ),
                (
                    "recouvrement_encaisser",
                    models.BooleanField(
                        default=False, verbose_name="Enregistrer des encaissements"
                    ),
                ),
                (
                    "recouvrement_reverser",
                    models.BooleanField(
                        default=False, verbose_name="Effectuer des reversements"
                    ),
                ),
                (
                    "recouvrement_point_global",
                    models.BooleanField(
                        default=False, verbose_name="Générer des points globaux"
                    ),
                ),
                (
                    "factures_voir",
                    models.BooleanField(default=True, verbose_name="Voir les factures"),
                ),
                (
                    "factures_creer",
                    models.BooleanField(
                        default=False, verbose_name="Créer des factures"
                    ),
                ),
                (
                    "factures_modifier",
                    models.BooleanField(
                        default=False, verbose_name="Modifier les factures"
                    ),
                ),
                (
                    "factures_supprimer",
                    models.BooleanField(
                        default=False, verbose_name="Supprimer des factures"
                    ),
                ),
                (
                    "factures_normaliser_mecef",
                    models.BooleanField(default=False, verbose_name="Normaliser MECeF"),
                ),
                (
                    "factures_avoir",
                    models.BooleanField(default=False, verbose_name="Créer des avoirs"),
                ),
                (
                    "memoires_voir",
                    models.BooleanField(default=True, verbose_name="Voir les mémoires"),
                ),
                (
                    "memoires_creer",
                    models.BooleanField(
                        default=False, verbose_name="Créer des mémoires"
                    ),
                ),
                (
                    "memoires_modifier",
                    models.BooleanField(
                        default=False, verbose_name="Modifier les mémoires"
                    ),
                ),
                (
                    "memoires_soumettre",
                    models.BooleanField(
                        default=False, verbose_name="Soumettre les mémoires"
                    ),
                ),
                (
                    "memoires_paiement_global",
                    models.BooleanField(
                        default=False, verbose_name="Enregistrer paiements globaux"
                    ),
                ),
                (
                    "tresorerie_voir",
                    models.BooleanField(
                        default=False, verbose_name="Voir la trésorerie"
                    ),
                ),
                (
                    "tresorerie_mouvements",
                    models.BooleanField(
                        default=False, verbose_name="Créer des mouvements"
                    ),
                ),
                (
                    "tresorerie_rapprochement",
                    models.BooleanField(
                        default=False, verbose_name="Rapprochement bancaire"
                    ),
                ),
                (
                    "tresorerie_voir_soldes",
                    models.BooleanField(
                        default=False, verbose_name="Voir les soldes des comptes"
                    ),
                ),
                (
                    "comptabilite_voir",
                    models.BooleanField(
                        default=False, verbose_name="Voir la comptabilité"
                    ),
                ),
                (
                    "comptabilite_ecritures",
                    models.BooleanField(
                        default=False, verbose_name="Saisir des écritures"
                    ),
                ),
                (
                    "comptabilite_cloture",
                    models.BooleanField(
                        default=False, verbose_name="Clôturer des périodes"
                    ),
                ),
                (
                    "comptabilite_etats",
                    models.BooleanField(
                        default=False, verbose_name="Générer les états financiers"
                    ),
                ),
                (
                    "gerance_voir",
                    models.BooleanField(default=False, verbose_name="Voir la gérance"),
                ),
                (
                    "gerance_biens",
                    models.BooleanField(default=False, verbose_name="Gérer les biens"),
                ),
                (
                    "gerance_baux",
                    models.BooleanField(default=False, verbose_name="Gérer les baux"),
                ),
                (
                    "gerance_quittances",
                    models.BooleanField(
                        default=False, verbose_name="Générer des quittances"
                    ),
                ),
                (
                    "gerance_reversements",
                    models.BooleanField(
                        default=False, verbose_name="Reversements propriétaires"
                    ),
                ),
                (
                    "agenda_voir",
                    models.BooleanField(default=True, verbose_name="Voir l'agenda"),
                ),
                (
                    "agenda_creer",
                    models.BooleanField(
                        default=True, verbose_name="Créer des événements"
                    ),
                ),
                (
                    "agenda_modifier_tous",
                    models.BooleanField(
                        default=False, verbose_name="Modifier tous les événements"
                    ),
                ),
                (
                    "agenda_taches",
                    models.BooleanField(default=True, verbose_name="Gérer les tâches"),
                ),
                (
                    "documents_voir",
                    models.BooleanField(
                        default=True, verbose_name="Voir les documents"
                    ),
                ),
                (
                    "documents_uploader",
                    models.BooleanField(
                        default=True, verbose_name="Uploader des documents"
                    ),
                ),
                (
                    "documents_supprimer",
                    models.BooleanField(
                        default=False, verbose_name="Supprimer des documents"
                    ),
                ),
                (
                    "documents_tous_dossiers",
                    models.BooleanField(
                        default=False, verbose_name="Accéder à tous les dossiers"
                    ),
                ),
                (
                    "rh_voir",
                    models.BooleanField(default=False, verbose_name="Voir les RH"),
                ),
                (
                    "rh_employes",
                    models.BooleanField(
                        default=False, verbose_name="Gérer les employés"
                    ),
                ),
                (
                    "rh_conges",
                    models.BooleanField(default=False, verbose_name="Gérer les congés"),
                ),
                (
                    "rh_paie",
                    models.BooleanField(default=False, verbose_name="Gérer la paie"),
                ),
                (
                    "parametres_voir",
                    models.BooleanField(
                        default=False, verbose_name="Voir les paramètres"
                    ),
                ),
                (
                    "parametres_modifier",
                    models.BooleanField(
                        default=False, verbose_name="Modifier les paramètres"
                    ),
                ),
                (
                    "parametres_utilisateurs",
                    models.BooleanField(
                        default=False, verbose_name="Gérer les utilisateurs"
                    ),
                ),
                (
                    "parametres_permissions",
                    models.BooleanField(
                        default=False, verbose_name="Gérer les permissions"
                    ),
                ),
                (
                    "rapports_voir",
                    models.BooleanField(
                        default=False, verbose_name="Voir les rapports"
                    ),
                ),
                (
                    "rapports_generer",
                    models.BooleanField(
                        default=False, verbose_name="Générer des rapports"
                    ),
                ),
                (
                    "exports_excel",
                    models.BooleanField(
                        default=False, verbose_name="Exporter en Excel"
                    ),
                ),
                (
                    "exports_pdf",
                    models.BooleanField(default=True, verbose_name="Exporter en PDF"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granulaires_modifiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_granulaires",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissions granulaires",
                "verbose_name_plural": "Permissions granulaires",
            },
        ),
    ]
