# Generated by Django 5.2.8 on 2025-11-29 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0015_permissionsgranulaires"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la session"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sql_file", "Fichier SQL"),
                            ("csv", "Fichier CSV"),
                            ("excel", "Fichier Excel"),
                            ("direct_db", "Connexion directe base"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fichier_source",
                    models.FileField(blank=True, null=True, upload_to="imports/"),
                ),
                ("total_lignes", models.PositiveIntegerField(default=0)),
                ("dossiers_trouves", models.PositiveIntegerField(default=0)),
                ("parties_trouvees", models.PositiveIntegerField(default=0)),
                ("doublons_detectes", models.PositiveIntegerField(default=0)),
                ("erreurs_detectees", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("analyse", "Analyse terminée"),
                            ("valide", "Validé"),
                            ("importe", "Importé"),
                            ("erreur", "Erreur"),
                            ("annule", "Annulé"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                (
                    "progression",
                    models.PositiveIntegerField(
                        default=0, help_text="Pourcentage de progression"
                    ),
                ),
                (
                    "rapport_json",
                    models.TextField(blank=True, help_text="Rapport détaillé en JSON"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session d'import",
                "verbose_name_plural": "Sessions d'import",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DossierImportTemp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_originale",
                    models.CharField(
                        max_length=500, verbose_name="Référence originale"
                    ),
                ),
                (
                    "donnees_brutes",
                    models.TextField(blank=True, help_text="Données JSON brutes"),
                ),
                ("numero_ordre", models.CharField(blank=True, max_length=20)),
                ("mois_creation", models.PositiveIntegerField(blank=True, null=True)),
                ("annee_creation", models.PositiveIntegerField(blank=True, null=True)),
                ("date_ouverture", models.DateField(blank=True, null=True)),
                ("demandeur_nom", models.CharField(blank=True, max_length=300)),
                ("demandeur_prenom", models.CharField(blank=True, max_length=100)),
                ("demandeur_adresse", models.TextField(blank=True)),
                ("demandeur_telephone", models.CharField(blank=True, max_length=50)),
                ("demandeur_email", models.CharField(blank=True, max_length=200)),
                ("defendeur_nom", models.CharField(blank=True, max_length=300)),
                ("defendeur_prenom", models.CharField(blank=True, max_length=100)),
                ("defendeur_adresse", models.TextField(blank=True)),
                ("defendeur_telephone", models.CharField(blank=True, max_length=50)),
                ("defendeur_email", models.CharField(blank=True, max_length=200)),
                (
                    "montant_principal",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "montant_interets",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                (
                    "montant_frais",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=15, null=True
                    ),
                ),
                ("intitule_genere", models.CharField(blank=True, max_length=500)),
                ("nouvelle_reference", models.CharField(blank=True, max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("importe", "Importé"),
                            ("doublon", "Doublon détecté"),
                            ("erreur", "Erreur"),
                            ("ignore", "Ignoré"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("message_erreur", models.TextField(blank=True)),
                (
                    "defendeur_existant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports_defendeur",
                        to="gestion.partie",
                    ),
                ),
                (
                    "demandeur_existant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports_demandeur",
                        to="gestion.partie",
                    ),
                ),
                (
                    "dossier_cree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_source",
                        to="gestion.dossier",
                    ),
                ),
                (
                    "dossier_existant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier existant correspondant (si doublon)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imports_correspondants",
                        to="gestion.dossier",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers_temp",
                        to="gestion.sessionimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier import temporaire",
                "verbose_name_plural": "Dossiers import temporaires",
                "ordering": ["annee_creation", "mois_creation", "numero_ordre"],
            },
        ),
    ]
