# Generated by Django 5.2.9 on 2025-12-06 00:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_dossiervirtuel_type_dossier_and_more"),
        ("gestion", "0018_add_dossier_indexes"),
        ("hr", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="est_client_assujetti_aib",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si le client est assujetti à l'AIB (retenue 3%)",
                verbose_name="Client assujetti AIB",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="montant_aib",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Montant AIB"
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="net_a_payer",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Net à payer"
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="taux_aib",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.00"),
                max_digits=5,
                verbose_name="Taux AIB (%)",
            ),
        ),
        migrations.CreateModel(
            name="ActeSecurise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_verification",
                    models.CharField(
                        db_index=True,
                        max_length=25,
                        unique=True,
                        verbose_name="Code de vérification",
                    ),
                ),
                (
                    "type_acte",
                    models.CharField(
                        choices=[
                            ("signification", "Signification"),
                            ("constat", "Procès-verbal de constat"),
                            ("sommation", "Sommation"),
                            ("commandement", "Commandement de payer"),
                            ("saisie", "Procès-verbal de saisie"),
                            ("inventaire", "Inventaire"),
                            ("citation", "Citation à comparaître"),
                            ("notification", "Notification"),
                            ("proces_verbal", "Procès-verbal"),
                            ("autre", "Autre acte"),
                        ],
                        max_length=50,
                        verbose_name="Type d'acte",
                    ),
                ),
                (
                    "titre_acte",
                    models.CharField(max_length=255, verbose_name="Titre de l'acte"),
                ),
                ("date_acte", models.DateField(verbose_name="Date de l'acte")),
                (
                    "parties_resume",
                    models.TextField(
                        help_text="Ex: BANQUE XYZ c/ M. DUPONT Jean",
                        verbose_name="Parties",
                    ),
                ),
                (
                    "hash_contenu",
                    models.CharField(
                        help_text="SHA-256 du contenu PDF",
                        max_length=64,
                        verbose_name="Hash du document",
                    ),
                ),
                (
                    "hash_algorithme",
                    models.CharField(
                        default="SHA256", max_length=10, verbose_name="Algorithme"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "nombre_verifications",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vérifications"
                    ),
                ),
                (
                    "derniere_verification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière vérification"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour invalider un acte (erreur, annulation)",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rh.collaborateur",
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actes_securises",
                        to="documents.document",
                        verbose_name="Document associé",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actes_securises",
                        to="gestion.dossier",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acte sécurisé",
                "verbose_name_plural": "Actes sécurisés",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["code_verification"],
                        name="gestion_act_code_ve_bde18d_idx",
                    ),
                    models.Index(
                        fields=["dossier", "-date_acte"],
                        name="gestion_act_dossier_1663b4_idx",
                    ),
                ],
            },
        ),
    ]
