# Generated by Django 5.2.9 on 2025-12-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0019_aib_facture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignefacture",
            name="enregistrement",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Droit d'enregistrement",
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="groupe_taxation",
            field=models.CharField(
                choices=[("A", "Exonéré"), ("B", "TVA 18%"), ("E", "TPS")],
                default="E",
                max_length=1,
                verbose_name="Groupe de taxation",
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="honoraires",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Honoraires"
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="montant_ht",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Montant HT"
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="montant_ttc",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Montant TTC"
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="montant_tva",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Montant TVA"
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="taux_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux TVA appliqué",
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="timbre",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Droit de timbre",
            ),
        ),
        migrations.AddField(
            model_name="lignefacture",
            name="type_ligne",
            field=models.CharField(
                choices=[("acte", "Acte"), ("debours", "Débours")],
                default="acte",
                max_length=10,
                verbose_name="Type de ligne",
            ),
        ),
    ]
