# Generated by Django 5.2.9 on 2025-12-06 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0020_enrichir_lignefacture_mecef"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, unique=True, verbose_name="Numéro"),
                ),
                (
                    "date_emission",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "date_validite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de validité"
                    ),
                ),
                ("client", models.CharField(max_length=200, verbose_name="Client")),
                (
                    "client_adresse",
                    models.TextField(blank=True, verbose_name="Adresse client"),
                ),
                (
                    "ifu",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="IFU client"
                    ),
                ),
                ("objet", models.TextField(blank=True, verbose_name="Objet")),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant HT",
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant TTC",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux TVA",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoyee", "Envoyée"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("expiree", "Expirée"),
                            ("convertie", "Convertie en facture"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proformas_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proformas",
                        to="gestion.dossier",
                        verbose_name="Dossier",
                    ),
                ),
                (
                    "facture_generee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proforma_origine",
                        to="gestion.facture",
                        verbose_name="Facture générée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proforma",
                "verbose_name_plural": "Proformas",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LigneProforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                ("quantite", models.IntegerField(default=1, verbose_name="Quantité")),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "type_ligne",
                    models.CharField(
                        choices=[("acte", "Acte"), ("debours", "Débours")],
                        default="acte",
                        max_length=10,
                        verbose_name="Type de ligne",
                    ),
                ),
                (
                    "groupe_taxation",
                    models.CharField(
                        choices=[("A", "Exonéré"), ("B", "TVA 18%"), ("E", "TPS")],
                        default="E",
                        max_length=1,
                        verbose_name="Groupe de taxation",
                    ),
                ),
                (
                    "honoraires",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Honoraires",
                    ),
                ),
                (
                    "timbre",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Droit de timbre",
                    ),
                ),
                (
                    "enregistrement",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Droit d'enregistrement",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux TVA",
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant HT",
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant TTC",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gestion.proforma",
                        verbose_name="Proforma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de proforma",
                "verbose_name_plural": "Lignes de proforma",
                "ordering": ["id"],
            },
        ),
    ]
