# Generated by Django 5.2.9 on 2025-12-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0024_actedossier"),
    ]

    operations = []
