# Generated by Django 5.2.9 on 2025-12-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0025_merge_0019_actesecurise_0024_actedossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignefacture",
            name="type_ligne",
            field=models.CharField(
                choices=[("honoraire", "Honoraire"), ("debours", "Débours")],
                default="honoraire",
                max_length=20,
                verbose_name="Type de ligne",
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("convertie", "Convertie en facture"),
                ],
                default="brouillon",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.CreateModel(
            name="DeboursDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intitule",
                    models.CharField(
                        help_text="Ex: Frais d'obtention ordonnance d'injonction de payer",
                        max_length=500,
                        verbose_name="Description du débours",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Montant (FCFA)"
                    ),
                ),
                ("date_debours", models.DateField(verbose_name="Date du débours")),
                (
                    "est_facture",
                    models.BooleanField(default=False, verbose_name="Facturé"),
                ),
                (
                    "date_facturation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de facturation"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debours_autonomes",
                        to="gestion.dossier",
                        verbose_name="Dossier",
                    ),
                ),
                (
                    "ligne_facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debours_source",
                        to="gestion.lignefacture",
                        verbose_name="Ligne de facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Débours autonome",
                "verbose_name_plural": "Débours autonomes",
                "ordering": ["-date_debours", "-date_creation"],
            },
        ),
    ]
