"""
Django settings for etude_huissier project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En production, définir la variable d'environnement DJANGO_SECRET_KEY
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ea+p-1a1cizds1ln#fm_w1s6twc2$b_wa$v)xx+$0)&(0s&8qh'  # Clé de développement uniquement
)

# SECURITY WARNING: don't run with debug turned on in production!
# En production, définir DJANGO_DEBUG=False dans les variables d'environnement
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# PRODUCTION: Définir les hosts autorisés (ex: ['etude-huissier.bj', 'www.etude-huissier.bj'])
# ALLOWED_HOSTS = ['*']  # NE PAS UTILISER EN PRODUCTION
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']  # Développement uniquement


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",  # Django Channels pour WebSocket
    "gestion",
    "comptabilite",
    "rh",
    "documents",
    "agenda",
    "parametres",
    "tresorerie",
    "gerance",
    "recouvrement",
    "portail_client",
    "chatbot",  # Module Assistant IA / Chatbot
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "etude_huissier.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "etude_huissier.wsgi.application"
ASGI_APPLICATION = "etude_huissier.asgi.application"

# Django Channels - Configuration WebSocket pour Chatbot
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
        # En production, utiliser Redis:
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #     "hosts": [("127.0.0.1", 6379)],
        # },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Porto-Novo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'gestion.Utilisateur'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 heures en secondes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Fermer la session à la fermeture du navigateur
SESSION_SAVE_EVERY_REQUEST = True  # Réinitialise le timer à chaque requête

# =============================================================================
# PARAMÈTRES DE SÉCURITÉ
# =============================================================================
# Ces paramètres sont commentés pour le développement local.
# ACTIVER EN PRODUCTION en décommentant les lignes appropriées.

# Sécurité des cookies
if not DEBUG:
    SESSION_COOKIE_SECURE = True      # Cookie session uniquement via HTTPS
    SESSION_COOKIE_HTTPONLY = True    # Cookie non accessible via JavaScript
    CSRF_COOKIE_SECURE = True         # Cookie CSRF uniquement via HTTPS
    CSRF_COOKIE_HTTPONLY = True       # Cookie CSRF non accessible via JavaScript

# Protection HTTPS (activer uniquement si HTTPS configuré)
if not DEBUG:
    SECURE_SSL_REDIRECT = True                  # Rediriger HTTP vers HTTPS
    SECURE_HSTS_SECONDS = 31536000              # 1 an de HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True       # HSTS pour sous-domaines
    SECURE_HSTS_PRELOAD = True                  # Autoriser le preloading HSTS
    SECURE_CONTENT_TYPE_NOSNIFF = True          # Empêcher le sniffing MIME
    SECURE_BROWSER_XSS_FILTER = True            # Activer filtre XSS navigateur
    SECURE_REFERRER_POLICY = 'same-origin'      # Politique de referrer

# Protection contre le clickjacking (toujours actif)
X_FRAME_OPTIONS = 'DENY'

# =============================================================================

# Email settings (pour le mot de passe oublié)
# En développement, les emails sont affichés dans la console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# En production, configurez un vrai serveur SMTP :
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre-email@example.com'
# EMAIL_HOST_PASSWORD = 'votre-mot-de-passe'
# DEFAULT_FROM_EMAIL = 'Étude Me BIAOU <no-reply@etude-biaou.com>'
