# Generated by Django 5.2.8 on 2025-11-27 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "gestion",
            "0002_alter_acteprocedure_options_alter_tauxlegal_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stockage_local_path",
                    models.CharField(
                        default="/media/documents",
                        max_length=500,
                        verbose_name="Chemin de stockage local",
                    ),
                ),
                (
                    "limite_upload_mo",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Limite upload (Mo)"
                    ),
                ),
                (
                    "types_autorises",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Extensions autorisées"
                    ),
                ),
                (
                    "logo_etude",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/",
                        verbose_name="Logo de l'étude",
                    ),
                ),
                (
                    "nom_etude",
                    models.CharField(
                        default="", max_length=200, verbose_name="Nom de l'étude"
                    ),
                ),
                (
                    "adresse_etude",
                    models.TextField(default="", verbose_name="Adresse de l'étude"),
                ),
                (
                    "telephone_etude",
                    models.CharField(
                        default="", max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email_etude",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "ifu_etude",
                    models.CharField(default="", max_length=50, verbose_name="IFU"),
                ),
                (
                    "rccm_etude",
                    models.CharField(default="", max_length=50, verbose_name="RCCM"),
                ),
                (
                    "nom_huissier",
                    models.CharField(
                        default="", max_length=200, verbose_name="Nom de l'huissier"
                    ),
                ),
                (
                    "qualite_huissier",
                    models.CharField(
                        default="Huissier de Justice",
                        max_length=100,
                        verbose_name="Qualité",
                    ),
                ),
                (
                    "signature_huissier",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/",
                        verbose_name="Signature de l'huissier",
                    ),
                ),
                (
                    "cachet_etude",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="config/",
                        verbose_name="Cachet de l'étude",
                    ),
                ),
                (
                    "duree_partage_defaut",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Durée de partage par défaut (jours)"
                    ),
                ),
                (
                    "autoriser_partage_public",
                    models.BooleanField(
                        default=False, verbose_name="Autoriser le partage public"
                    ),
                ),
                (
                    "duree_retention_corbeille",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Rétention corbeille (jours)"
                    ),
                ),
                (
                    "ocr_actif",
                    models.BooleanField(default=False, verbose_name="OCR activé"),
                ),
                (
                    "audit_actif",
                    models.BooleanField(default=True, verbose_name="Audit activé"),
                ),
                (
                    "duree_retention_audit",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Rétention audit (jours)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Documents",
                "verbose_name_plural": "Configuration Documents",
            },
        ),
        migrations.CreateModel(
            name="NumeroActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField(unique=True)),
                ("dernier_numero", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Numéro d'Acte",
                "verbose_name_plural": "Numéros d'Actes",
            },
        ),
        migrations.CreateModel(
            name="CloudConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("google_drive", "Google Drive"),
                            ("dropbox", "Dropbox"),
                            ("onedrive", "OneDrive"),
                            ("local", "Stockage Local"),
                            ("s3", "Amazon S3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nom_compte",
                    models.CharField(max_length=200, verbose_name="Nom du compte"),
                ),
                (
                    "email_compte",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "dossier_racine",
                    models.CharField(
                        default="/", max_length=500, verbose_name="Dossier racine"
                    ),
                ),
                (
                    "espace_total",
                    models.BigIntegerField(
                        default=0, verbose_name="Espace total (octets)"
                    ),
                ),
                (
                    "espace_utilise",
                    models.BigIntegerField(
                        default=0, verbose_name="Espace utilisé (octets)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("erreur", "Erreur de connexion"),
                            ("expire", "Token expiré"),
                        ],
                        default="inactif",
                        max_length=20,
                    ),
                ),
                (
                    "est_principal",
                    models.BooleanField(
                        default=False, verbose_name="Stockage principal"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Configuration additionnelle",
                    ),
                ),
                ("date_connexion", models.DateTimeField(auto_now_add=True)),
                ("derniere_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connexion Cloud",
                "verbose_name_plural": "Connexions Cloud",
                "ordering": ["-est_principal", "service", "nom_compte"],
            },
        ),
        migrations.CreateModel(
            name="DossierVirtuel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "type_dossier",
                    models.CharField(
                        choices=[
                            ("racine", "Racine"),
                            ("dossier_juridique", "Dossier Juridique"),
                            ("actes", "01_Actes"),
                            ("decisions", "02_Decisions_Titres"),
                            ("pieces", "03_Pieces_Client"),
                            ("correspondances", "04_Correspondances"),
                            ("facturation", "05_Facturation"),
                            ("divers", "06_Divers"),
                            ("archives", "Archives"),
                            ("modeles", "Modèles"),
                            ("corbeille", "Corbeille"),
                            ("personnel", "Personnel"),
                        ],
                        default="personnel",
                        max_length=50,
                    ),
                ),
                (
                    "chemin",
                    models.CharField(max_length=1000, verbose_name="Chemin complet"),
                ),
                (
                    "cloud_id",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="ID Cloud"
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#1a365d", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="folder", max_length=50, verbose_name="Icône"
                    ),
                ),
                (
                    "est_systeme",
                    models.BooleanField(default=False, verbose_name="Dossier système"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cloud_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.cloudconnection",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_virtuels_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier_juridique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers_virtuels",
                        to="gestion.dossier",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_dossiers",
                        to="documents.dossiervirtuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier Virtuel",
                "verbose_name_plural": "Dossiers Virtuels",
                "ordering": ["chemin"],
                "unique_together": {("parent", "nom")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "nom_original",
                    models.CharField(max_length=255, verbose_name="Nom original"),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("acte_commandement", "Commandement de payer"),
                            ("acte_signification", "Signification de décision"),
                            ("acte_pv_saisie", "Procès-verbal de saisie"),
                            ("acte_pv_constat", "Procès-verbal de constat"),
                            ("acte_denonciation", "Dénonciation"),
                            ("acte_autre", "Autre acte"),
                            ("decision_justice", "Décision de justice"),
                            ("titre_executoire", "Titre exécutoire"),
                            ("jugement", "Jugement"),
                            ("ordonnance", "Ordonnance"),
                            ("facture", "Facture"),
                            ("devis", "Devis"),
                            ("recu", "Reçu de paiement"),
                            ("note_honoraires", "Note d'honoraires"),
                            ("decompte", "Décompte de recouvrement"),
                            ("lettre_mise_demeure", "Lettre de mise en demeure"),
                            ("lettre_relance", "Lettre de relance"),
                            ("courrier", "Courrier"),
                            ("email", "Email archivé"),
                            ("fiche_dossier", "Fiche du dossier"),
                            ("piece_identite", "Pièce d'identité"),
                            ("contrat", "Contrat"),
                            ("attestation", "Attestation"),
                            ("photo", "Photo"),
                            ("scan", "Document scanné"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("fichier", models.FileField(upload_to="documents/%Y/%m/")),
                ("chemin_local", models.CharField(blank=True, max_length=1000)),
                ("cloud_id", models.CharField(blank=True, max_length=500, null=True)),
                ("chemin_cloud", models.CharField(blank=True, max_length=1000)),
                (
                    "taille",
                    models.BigIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("extension", models.CharField(blank=True, max_length=20)),
                (
                    "hash_md5",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Hash MD5"
                    ),
                ),
                (
                    "hash_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash SHA256"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("genere", "Généré"),
                            ("valide", "Validé"),
                            ("signe", "Signé"),
                            ("archive", "Archivé"),
                            ("supprime", "Supprimé"),
                        ],
                        default="genere",
                        max_length=20,
                    ),
                ),
                (
                    "est_modele",
                    models.BooleanField(default=False, verbose_name="Est un modèle"),
                ),
                (
                    "est_genere",
                    models.BooleanField(
                        default=False, verbose_name="Généré automatiquement"
                    ),
                ),
                (
                    "contenu_texte",
                    models.TextField(blank=True, verbose_name="Contenu OCR"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_suppression", models.DateTimeField(blank=True, null=True)),
                (
                    "cloud_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.cloudconnection",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "dossier_juridique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="gestion.dossier",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_modifies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.dossiervirtuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ModeleDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom du modèle")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code unique"
                    ),
                ),
                (
                    "type_modele",
                    models.CharField(
                        choices=[
                            ("acte", "Acte de procédure"),
                            ("courrier", "Courrier/Lettre"),
                            ("facture", "Facture"),
                            ("fiche", "Fiche dossier"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "contenu_template",
                    models.TextField(
                        verbose_name="Contenu du template (HTML/Markdown)"
                    ),
                ),
                (
                    "format_sortie",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("docx", "Word DOCX"),
                            ("pdf", "PDF"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "fichier_template",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="modeles/",
                        verbose_name="Fichier template (DOCX)",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Variables disponibles"
                    ),
                ),
                (
                    "variables_exemple",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Exemples de variables"
                    ),
                ),
                (
                    "avec_entete",
                    models.BooleanField(
                        default=True, verbose_name="Inclure en-tête étude"
                    ),
                ),
                (
                    "avec_pied_page",
                    models.BooleanField(
                        default=True, verbose_name="Inclure pied de page"
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("portrait", "Portrait"), ("paysage", "Paysage")],
                        default="portrait",
                        max_length=10,
                    ),
                ),
                (
                    "marge_haut",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Marge haute (mm)"
                    ),
                ),
                (
                    "marge_bas",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Marge basse (mm)"
                    ),
                ),
                (
                    "marge_gauche",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Marge gauche (mm)"
                    ),
                ),
                (
                    "marge_droite",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Marge droite (mm)"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "est_systeme",
                    models.BooleanField(default=False, verbose_name="Modèle système"),
                ),
                ("ordre_affichage", models.PositiveIntegerField(default=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modeles_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de Document",
                "verbose_name_plural": "Modèles de Documents",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="GenerationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variables", models.JSONField(default=dict)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("erreur", "Erreur"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("message_erreur", models.TextField(blank=True)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_generation", models.DateTimeField(blank=True, null=True)),
                (
                    "duree_generation",
                    models.FloatField(default=0, verbose_name="Durée (secondes)"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_genere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation",
                        to="documents.document",
                    ),
                ),
                (
                    "dossier_juridique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.dossier",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.facture",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generations",
                        to="documents.modeledocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Génération de Document",
                "verbose_name_plural": "Générations de Documents",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="PartageDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("lien", models.CharField(blank=True, max_length=500)),
                (
                    "type_partage",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture seule"),
                            ("telechargement", "Téléchargement"),
                            ("modification", "Modification"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
                (
                    "mot_de_passe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mot_de_passe_hash", models.CharField(blank=True, max_length=128)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                (
                    "nombre_acces_max",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'accès maximum (0 = illimité)"
                    ),
                ),
                (
                    "nombre_acces",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'accès"
                    ),
                ),
                ("destinataire_email", models.EmailField(blank=True, max_length=254)),
                ("destinataire_nom", models.CharField(blank=True, max_length=200)),
                ("actif", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages",
                        to="documents.document",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages",
                        to="documents.dossiervirtuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partage de Document",
                "verbose_name_plural": "Partages de Documents",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="AccesPartage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_acces", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("action", models.CharField(default="consultation", max_length=50)),
                (
                    "partage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acces",
                        to="documents.partagedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès Partage",
                "verbose_name_plural": "Accès Partages",
                "ordering": ["-date_acces"],
            },
        ),
        migrations.CreateModel(
            name="SignatureElectronique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_signature",
                    models.CharField(
                        choices=[
                            ("manuscrite", "Signature manuscrite numérisée"),
                            ("cachet", "Cachet électronique"),
                            ("certificat", "Signature par certificat"),
                            ("externe", "Signature externe (DocuSign, etc.)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signataire_nom", models.CharField(max_length=200)),
                ("signataire_email", models.EmailField(blank=True, max_length=254)),
                (
                    "image_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Image de la signature",
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position X (px)"
                    ),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Position Y (px)"
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Page de signature"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de signature"),
                            ("signe", "Signé"),
                            ("refuse", "Refusé"),
                            ("expire", "Expiré"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_signature", models.DateTimeField(blank=True, null=True)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                ("hash_document", models.CharField(blank=True, max_length=64)),
                (
                    "certificat",
                    models.TextField(
                        blank=True, verbose_name="Certificat d'authenticité"
                    ),
                ),
                ("ip_signataire", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("service_externe", models.CharField(blank=True, max_length=50)),
                ("reference_externe", models.CharField(blank=True, max_length=200)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="documents.document",
                    ),
                ),
                (
                    "signataire_utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature Électronique",
                "verbose_name_plural": "Signatures Électroniques",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="AuditDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("lecture", "Lecture"),
                            ("modification", "Modification"),
                            ("suppression", "Suppression"),
                            ("restauration", "Restauration"),
                            ("telechargement", "Téléchargement"),
                            ("partage", "Partage"),
                            ("signature", "Signature"),
                            ("impression", "Impression"),
                            ("deplacement", "Déplacement"),
                            ("copie", "Copie"),
                            ("archivage", "Archivage"),
                            ("generation", "Génération"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to="documents.document",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to="documents.dossiervirtuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Document",
                "verbose_name_plural": "Audits Documents",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["document", "-date"],
                        name="documents_a_documen_05ca62_idx",
                    ),
                    models.Index(
                        fields=["utilisateur", "-date"],
                        name="documents_a_utilisa_ec9b8a_idx",
                    ),
                    models.Index(
                        fields=["action", "-date"], name="documents_a_action_5620da_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VersionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_version", models.PositiveIntegerField()),
                ("fichier", models.FileField(upload_to="documents/versions/%Y/%m/")),
                ("taille", models.BigIntegerField(default=0)),
                ("hash_md5", models.CharField(blank=True, max_length=32)),
                ("commentaire", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de Document",
                "verbose_name_plural": "Versions de Documents",
                "ordering": ["-numero_version"],
                "unique_together": {("document", "numero_version")},
            },
        ),
    ]
