# Generated by Django 5.2.8 on 2025-11-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossiervirtuel",
            name="type_dossier",
            field=models.CharField(
                choices=[
                    ("racine", "Racine"),
                    ("annee", "Année"),
                    ("dossier_juridique", "Dossier Juridique"),
                    ("projets_actes", "Projets d'actes"),
                    ("actes_formalises", "Actes formalisés"),
                    ("pieces", "Pièces"),
                    ("courrier_arrivee", "Courrier arrivée"),
                    ("courrier_depart", "Courrier départ"),
                    ("factures", "Factures"),
                    ("actes_exterieurs", "Actes extérieurs"),
                    ("actes", "01_Actes"),
                    ("decisions", "02_Decisions_Titres"),
                    ("correspondances", "04_Correspondances"),
                    ("facturation", "05_Facturation"),
                    ("divers", "06_Divers"),
                    ("archives", "Archives"),
                    ("modeles", "Modèles"),
                    ("corbeille", "Corbeille"),
                    ("personnel", "Personnel"),
                ],
                default="personnel",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="modeledocument",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_modeles_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
